export type DmsRoadmapItem={id:string;label:string;done:boolean;note?:string};
export type DmsRoadmapPhase={id:string;title:string;goal:string;items:DmsRoadmapItem[]};

export const DMS_ROADMAP_PHASES:DmsRoadmapPhase[]=[
  {
    id:'F1',
    title:'Fase 1 · Fundação e fonte única de verdade',
    goal:'Um veículo, cliente, fornecedor e lançamento financeiro devem existir uma única vez e ser reutilizados por todos os módulos.',
    items:[
      {id:'F1.01',label:'Estoque atual canônico único',done:true},
      {id:'F1.02',label:'Identidade estável do veículo com vehicleId',done:true},
      {id:'F1.03',label:'Cadastro mestre de veículo',done:true},
      {id:'F1.04',label:'PrepTrack ligado ao vehicleId',done:true},
      {id:'F1.05',label:'Financeiro da preparação ligado ao vehicleId',done:true},
      {id:'F1.06',label:'Cadastro mestre de cliente no backend',done:true},
      {id:'F1.07',label:'CRM e showroom criando/reutilizando customerId',done:true},
      {id:'F1.08',label:'Cadastro mestre de fornecedor no backend',done:true},
      {id:'F1.09',label:'Preparação aprovada criando/reutilizando supplierId',done:true},
      {id:'F1.10',label:'Razão financeiro único base',done:true},
      {id:'F1.11',label:'Trilha de auditoria base',done:true},
      {id:'F1.12',label:'Diagnóstico de integridade DMS',done:true},
      {id:'F1.13',label:'Migração dos dados antigos para IDs mestres',done:true},
      {id:'F1.14',label:'Validação automática contra duplicidades de mestre',done:true},
      {id:'F1.15',label:'Histórico de movimentos do estoque separado do estoque atual',done:true},
    ],
  },
  {
    id:'F2',
    title:'Fase 2 · Usuários, funções e segurança',
    goal:'Cada pessoa acessa somente o necessário para sua responsabilidade.',
    items:[
      {id:'F2.01',label:'Editar usuário existente',done:true},
      {id:'F2.02',label:'Padrões Gestor, Preparação e Financeiro/Caixa',done:true},
      {id:'F2.03',label:'Checkboxes de permissões por usuário para estoque, preparação e financeiro',done:true},
      {id:'F2.04',label:'Workspace enxuto para Preparação e Financeiro/Caixa',done:true},
      {id:'F2.05',label:'Separar solicitação de preparação da aprovação gerencial',done:true},
      {id:'F2.06',label:'Separar visão financeira de baixa financeira',done:true},
      {id:'F2.07',label:'Checkboxes para CRM, avaliações, propostas, documentos, ativos e relatórios',done:false},
      {id:'F2.08',label:'Permissões por unidade e múltiplas unidades por usuário',done:false},
      {id:'F2.09',label:'Aplicar permissões também no backend/API',done:false},
      {id:'F2.10',label:'Aplicar permissões nas regras Firestore',done:false},
      {id:'F2.11',label:'Auditar alteração de permissões e usuários',done:false},
      {id:'F2.12',label:'Bloqueio de autoaprovação em fluxos sensíveis',done:false},
    ],
  },
  {
    id:'F3',
    title:'Fase 3 · Estoque, compra e entrada do veículo',
    goal:'Explicar de onde cada carro veio, quanto custou, quem vendeu e como entrou na operação.',
    items:[
      {id:'F3.01',label:'Cadastro manual de veículo com FIPE',done:true},
      {id:'F3.02',label:'Importação de estoque sem duplicar fonte de verdade',done:true},
      {id:'F3.03',label:'Aging automático do estoque',done:true},
      {id:'F3.04',label:'Custo atual = compra + preparação aprovada',done:true},
      {id:'F3.05',label:'Avaliação aprovada virar intenção de compra',done:true},
      {id:'F3.06',label:'Pedido de compra do veículo',done:true},
      {id:'F3.07',label:'Cadastro do proprietário/vendedor do veículo',done:true},
      {id:'F3.08',label:'Origem da entrada: compra, troca, repasse ou consignação',done:true},
      {id:'F3.09',label:'Quitação de financiamento do veículo comprado',done:true},
      {id:'F3.10',label:'Débitos, multas e pendências na compra',done:true},
      {id:'F3.11',label:'Conta a pagar da compra',done:true},
      {id:'F3.12',label:'Formas e etapas do pagamento da compra',done:true},
      {id:'F3.13',label:'Checklist documental de entrada',done:true},
      {id:'F3.14',label:'Entrada formal no estoque após compra',done:true},
      {id:'F3.15',label:'Transferência entre unidades com histórico',done:true},
      {id:'F3.16',label:'Consignação com proprietário e vencimentos',done:true},
      {id:'F3.17',label:'Dossiê completo do custo de aquisição',done:true},
    ],
  },
  {
    id:'F4',
    title:'Fase 4 · Preparação e fornecedores',
    goal:'Controlar solicitação, aprovação, execução, custo e pagamento de cada serviço.',
    items:[
      {id:'F4.01',label:'Criação automática de ordem no PrepTrack',done:true},
      {id:'F4.02',label:'Lançamento de serviço, fornecedor, valor e prazo',done:true},
      {id:'F4.03',label:'Aprovação gerencial do serviço',done:true},
      {id:'F4.04',label:'Serviço aprovado gerando conta a pagar',done:true},
      {id:'F4.05',label:'Custo aprovado refletindo no custo do veículo',done:true},
      {id:'F4.06',label:'Pagamento do fornecedor ligado à placa/vehicleId',done:true},
      {id:'F4.07',label:'Histórico do veículo com solicitação, aprovação e pagamento',done:true},
      {id:'F4.08',label:'Rejeição de orçamento com motivo',done:true},
      {id:'F4.09',label:'Múltiplos orçamentos para o mesmo serviço',done:false},
      {id:'F4.10',label:'Anexo de orçamento, nota fiscal e comprovante',done:false},
      {id:'F4.11',label:'Fotos antes/depois da preparação',done:false},
      {id:'F4.12',label:'Retrabalho e garantia do fornecedor',done:false},
      {id:'F4.13',label:'SLA e indicadores por fornecedor',done:true},
      {id:'F4.14',label:'Cadastro/edição de fornecedor com dados bancários e Pix',done:true},
      {id:'F4.15',label:'Relatório de custo de preparação por carro e fornecedor',done:true},
    ],
  },
  {
    id:'F5',
    title:'Fase 5 · CRM, cliente e negociação',
    goal:'Levar o cliente do primeiro contato até uma proposta sem redigitação.',
    items:[
      {id:'F5.01',label:'CRM/showroom base',done:true},
      {id:'F5.02',label:'Cadastro mestre de cliente criado a partir do atendimento',done:true},
      {id:'F5.03',label:'Histórico de atendimento e follow-up',done:true},
      {id:'F5.04',label:'Propostas comerciais versionadas',done:true},
      {id:'F5.05',label:'Tela completa para consultar/editar cliente mestre',done:true},
      {id:'F5.06',label:'CPF/CNPJ, endereço e documentos do cliente',done:true},
      {id:'F5.07',label:'Deduplicação de clientes antigos',done:true},
      {id:'F5.08',label:'Proposta vinculada obrigatoriamente ao vehicleId',done:true},
      {id:'F5.09',label:'Reserva do veículo por proposta',done:true},
      {id:'F5.10',label:'Prazo de validade e expiração automática da reserva',done:false},
      {id:'F5.11',label:'Aceite digital da proposta',done:false},
      {id:'F5.12',label:'LGPD, consentimento e trilha de dados pessoais',done:false},
    ],
  },
  {
    id:'F6',
    title:'Fase 6 · Pedido de venda, financiamento e faturamento',
    goal:'Transformar proposta aceita em venda completa, sem atalhos paralelos.',
    items:[
      {id:'F6.01',label:'Pedido de Venda central',done:true},
      {id:'F6.02',label:'Proposta aceita gerar Pedido de Venda',done:true},
      {id:'F6.03',label:'Reserva automática do estoque ao abrir pedido',done:true},
      {id:'F6.04',label:'Aprovação gerencial da venda',done:true},
      {id:'F6.05',label:'Entrada/sinal do cliente',done:true},
      {id:'F6.06',label:'Financiamento com banco, status e retorno',done:true},
      {id:'F6.07',label:'Análise/liberação de crédito',done:true},
      {id:'F6.08',label:'Troca vinculada ao pedido',done:true},
      {id:'F6.09',label:'Troca aceita virar compra e novo estoque',done:true},
      {id:'F6.10',label:'Comissão ligada ao pedido de venda',done:true},
      {id:'F6.11',label:'Faturamento do veículo',done:true},
      {id:'F6.12',label:'Contas a receber geradas pelo faturamento',done:true},
      {id:'F6.13',label:'Checklist de entrega',done:true},
      {id:'F6.14',label:'Entrega registrada com data e responsável',done:true},
      {id:'F6.15',label:'Saída definitiva do estoque somente após evento correto',done:true},
      {id:'F6.16',label:'Cancelamento/estorno de venda com reversões automáticas',done:false},
    ],
  },
  {
    id:'F7',
    title:'Fase 7 · Financeiro completo',
    goal:'Todo real que entra ou sai deve ter origem, vencimento, parte, status e responsável.',
    items:[
      {id:'F7.01',label:'Contas a pagar base',done:true},
      {id:'F7.02',label:'Contas a receber base',done:true},
      {id:'F7.03',label:'Fluxo de caixa realizado e projetado inicial',done:true},
      {id:'F7.04',label:'Lançamento manual financeiro',done:true},
      {id:'F7.05',label:'Baixa de pagamento e recebimento',done:true},
      {id:'F7.06',label:'Bancos e contas bancárias',done:true},
      {id:'F7.07',label:'Caixas físicos por unidade',done:true},
      {id:'F7.08',label:'Parcelas e recorrências',done:true},
      {id:'F7.09',label:'Conciliação bancária',done:false},
      {id:'F7.10',label:'Plano de contas',done:true},
      {id:'F7.11',label:'Centros de custo',done:true},
      {id:'F7.12',label:'DRE gerencial',done:true},
      {id:'F7.13',label:'Comissões a pagar',done:true},
      {id:'F7.14',label:'Recebíveis de bancos/financiamento',done:true},
      {id:'F7.15',label:'Anexo de comprovantes e documentos financeiros',done:false},
      {id:'F7.16',label:'Estorno de baixa com aprovação e auditoria',done:false},
      {id:'F7.17',label:'Aging de contas e alertas de vencimento',done:true},
      {id:'F7.18',label:'Fechamento diário/mensal de caixa',done:false},
    ],
  },
  {
    id:'F8',
    title:'Fase 8 · Documentação, fiscal e pós-venda',
    goal:'Acompanhar a vida documental e fiscal do carro até depois da entrega.',
    items:[
      {id:'F8.01',label:'Dossiê documental do veículo',done:true},
      {id:'F8.02',label:'ATPV-e / transferência',done:false},
      {id:'F8.03',label:'CRLV e documentos de entrada/saída',done:false},
      {id:'F8.04',label:'Gravame',done:false},
      {id:'F8.05',label:'Multas e débitos',done:false},
      {id:'F8.06',label:'Despachante e custos documentais',done:false},
      {id:'F8.07',label:'Nota fiscal / integração fiscal',done:false},
      {id:'F8.08',label:'Upload e organização de documentos',done:false},
      {id:'F8.09',label:'Garantia do veículo vendido',done:false},
      {id:'F8.10',label:'Ocorrências de pós-venda',done:false},
      {id:'F8.11',label:'Custos de garantia/pós-venda',done:false},
      {id:'F8.12',label:'Pesquisa de satisfação e retorno do cliente',done:false},
    ],
  },
  {
    id:'F9',
    title:'Fase 9 · Gestão, BI e relatórios',
    goal:'Usar as transações reais do DMS como fonte dos indicadores.',
    items:[
      {id:'F9.01',label:'Dashboard operacional',done:true},
      {id:'F9.02',label:'Estoque por idade e custo de capital',done:true},
      {id:'F9.03',label:'Relatórios comerciais/showroom existentes',done:true},
      {id:'F9.04',label:'Dashboard 100% derivado das transações DMS',done:false},
      {id:'F9.05',label:'Rentabilidade real por veículo',done:false},
      {id:'F9.06',label:'Resultado por vendedor',done:false},
      {id:'F9.07',label:'Resultado por unidade',done:false},
      {id:'F9.08',label:'Resultado por fornecedor de preparação',done:false},
      {id:'F9.09',label:'Funil completo lead → proposta → venda → entrega',done:false},
      {id:'F9.10',label:'Painel de compras/captação',done:false},
      {id:'F9.11',label:'Painel financeiro e DRE',done:false},
      {id:'F9.12',label:'Alertas executivos de inconsistências e exceções',done:false},
    ],
  },
  {
    id:'F10',
    title:'Fase 10 · Multiempresa, SaaS e administração',
    goal:'Permitir vender o Motyq para várias lojas sem misturar dados ou configurações.',
    items:[
      {id:'F10.01',label:'Multiempresa base',done:true},
      {id:'F10.02',label:'Multiunidade base',done:true},
      {id:'F10.03',label:'Administração master de empresas',done:true},
      {id:'F10.04',label:'Planos Starter, Pro e Enterprise',done:true},
      {id:'F10.05',label:'Controle de mensalidade/bloqueio base',done:true},
      {id:'F10.06',label:'Gestão de usuários por empresa',done:true},
      {id:'F10.07',label:'Configuração de módulos por plano totalmente aplicada',done:false},
      {id:'F10.08',label:'Cobrança recorrente automatizada',done:false},
      {id:'F10.09',label:'Portal do cliente para cobrança/plano',done:false},
      {id:'F10.10',label:'Onboarding guiado de nova loja',done:false},
      {id:'F10.11',label:'Importador/migrador de dados de outro DMS',done:false},
      {id:'F10.12',label:'Ambiente demo totalmente isolado',done:false},
    ],
  },
  {
    id:'F11',
    title:'Fase 11 · Segurança, confiabilidade e operação',
    goal:'O sistema precisa ser confiável o bastante para carregar estoque, dinheiro e histórico real.',
    items:[
      {id:'F11.01',label:'Testes automatizados dos fluxos críticos',done:false},
      {id:'F11.02',label:'CI com typecheck, build e testes a cada alteração',done:true},
      {id:'F11.03',label:'Regras Firestore versionadas e publicadas por ambiente',done:false},
      {id:'F11.04',label:'Índices Firestore versionados',done:false},
      {id:'F11.05',label:'Backup periódico e procedimento de restauração',done:false},
      {id:'F11.06',label:'Migrações de dados versionadas',done:false},
      {id:'F11.07',label:'Auditoria imutável ou protegida contra edição',done:false},
      {id:'F11.08',label:'Monitoramento central de erros',done:false},
      {id:'F11.09',label:'Monitoramento de performance',done:false},
      {id:'F11.10',label:'Rotina automática de diagnóstico por tenant',done:false},
      {id:'F11.11',label:'Política de retenção e exclusão de dados/LGPD',done:false},
      {id:'F11.12',label:'Exportação de dados e trilha para auditoria',done:false},
    ],
  },
  {
    id:'F12',
    title:'Fase 12 · Expansão para concessionária completa',
    goal:'Recursos adicionais caso o Motyq avance de seminovos para concessionárias com pós-venda técnico.',
    items:[
      {id:'F12.01',label:'Ordem de serviço de oficina',done:false},
      {id:'F12.02',label:'Agenda de oficina',done:false},
      {id:'F12.03',label:'Estoque de peças',done:false},
      {id:'F12.04',label:'Requisição/baixa de peças por OS',done:false},
      {id:'F12.05',label:'Garantia de fábrica',done:false},
      {id:'F12.06',label:'Produtividade de técnicos',done:false},
      {id:'F12.07',label:'Integrações com montadoras',done:false},
    ],
  },
];

export const dmsRoadmapSummary=()=>{
  const items=DMS_ROADMAP_PHASES.flatMap(phase=>phase.items);
  const done=items.filter(item=>item.done).length;
  return{done,total:items.length,percent:items.length?Math.round(done/items.length*100):0};
};
