import React, { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, KeyRound, RefreshCw, ShieldAlert } from 'lucide-react';
import { assetGuardIntegrationService, AssetGuardRadarVehicle } from '../services/assetGuardIntegrationService';
import { assetGuardSlaConfigService } from '../services/assetGuardSlaConfigService';
import { storeScopedOperationalService } from '../services/storeScopedOperationalService';

type Tone='critical'|'warning'|'good'|'info';
type Alert={id:string;tone:Tone;title:string;text:string;metric?:string;};
type Props={companyId:string;storeId:string;storeName:string;onCountsChange?:(active:number,critical:number)=>void;};
const plateList=(items:AssetGuardRadarVehicle[])=>items.slice(0,3).map(item=>item.plate).join(', ')+(items.length>3?` +${items.length-3}`:'');

const AssetGuardSmartAlerts:React.FC<Props>=({companyId,storeId,storeName,onCountsChange})=>{
 const[alerts,setAlerts]=useState<Alert[]>([]);const[loading,setLoading]=useState(false);const[connected,setConnected]=useState(false);
 const load=async()=>{setLoading(true);try{const token=assetGuardIntegrationService.getToken(companyId);setConnected(Boolean(token));if(!token){setAlerts([{id:'not-connected',tone:'info',title:'Conecte o AssetGuard',text:'Abra o módulo AssetGuard e clique em “Conectar AssetGuard” para liberar alertas de manuais, chaves e transporte.'}]);onCountsChange?.(0,0);return;}const[stock,config]=await Promise.all([storeScopedOperationalService.getLatestStock(storeId,companyId),assetGuardSlaConfigService.get(companyId,storeId)]);const plates=Array.from(new Set(stock.map(item=>String(item.plate||'').toUpperCase().replace(/[^A-Z0-9]/g,'')).filter(plate=>/^[A-Z0-9]{7}$/.test(plate))));const radar=await assetGuardIntegrationService.getRadar(companyId,plates);if(!radar){setAlerts([]);onCountsChange?.(0,0);return;}const next:Alert[]=[];const missing=Math.max(plates.length-radar.summary.registered,0);if(missing>0)next.push({id:'missing-registration',tone:'warning',title:'Veículos do estoque sem cadastro no AssetGuard',text:`${missing} veículo(s) do estoque de ${storeName} ainda não possuem ficha de manual/chave.`,metric:`${missing} sem cadastro`});
 const criticalRequests=radar.vehicles.filter(item=>item.requestOpen&&item.waitingRequestHours>config.sendCriticalHours);const warningRequests=radar.vehicles.filter(item=>item.requestOpen&&item.waitingRequestHours>config.sendTargetHours&&item.waitingRequestHours<=config.sendCriticalHours);if(criticalRequests.length)next.push({id:'critical-request',tone:'critical',title:`Solicitação crítica acima de ${config.sendCriticalHours}h`,text:`${plateList(criticalRequests)} aguardam início do envio além do limite crítico da operação.`,metric:`${criticalRequests.length} crítica(s)`});if(warningRequests.length)next.push({id:'warning-request',tone:'warning',title:`Solicitação acima da meta de ${config.sendTargetHours}h`,text:`${plateList(warningRequests)} já saíram da faixa verde e precisam de atenção antes do limite de ${config.sendCriticalHours}h.`,metric:`${warningRequests.length} atenção`});
 const criticalTransit=radar.vehicles.filter(item=>item.inTransit&&item.transitHours>config.transitCriticalHours);const warningTransit=radar.vehicles.filter(item=>item.inTransit&&item.transitHours>config.transitTargetHours&&item.transitHours<=config.transitCriticalHours);if(criticalTransit.length)next.push({id:'critical-transit',tone:'critical',title:`Transporte crítico acima de ${config.transitCriticalHours}h`,text:`${plateList(criticalTransit)} continuam em malote/deslocamento sem confirmação de recebimento.`,metric:`${criticalTransit.length} crítico(s)`});if(warningTransit.length)next.push({id:'warning-transit',tone:'warning',title:`Transporte acima da meta de ${config.transitTargetHours}h`,text:`${plateList(warningTransit)} estão na faixa amarela e devem ser acompanhados antes de ${config.transitCriticalHours}h.`,metric:`${warningTransit.length} atenção`});
 const outside=radar.vehicles.filter(item=>item.outsideSaleStore);if(outside.length)next.push({id:'outside-sale-store',tone:'warning',title:'Venda/necessidade com item em outra unidade',text:`${plateList(outside)} têm manual ou chave fora da unidade indicada para a entrega.`,metric:`${outside.length} veículo(s)`});if(!next.length)next.push({id:'assetguard-ok',tone:'good',title:'AssetGuard dentro das metas',text:`As placas de ${storeName} estão dentro do SLA ativo: envio até ${config.sendTargetHours}h e transporte até ${config.transitTargetHours}h.`,metric:'Faixa verde'});setAlerts(next);const active=next.filter(item=>item.tone==='critical'||item.tone==='warning').length;const critical=next.filter(item=>item.tone==='critical').length;onCountsChange?.(active,critical);}catch(error){const text=error instanceof Error?error.message:'Não foi possível carregar o radar do AssetGuard.';setAlerts([{id:'assetguard-error',tone:'warning',title:'AssetGuard precisa de atenção',text}]);setConnected(Boolean(assetGuardIntegrationService.getToken(companyId)));onCountsChange?.(1,0);}finally{setLoading(false);}};
 useEffect(()=>{load();const refresh=()=>load();window.addEventListener('dealmaster:assetguard-connected',refresh);window.addEventListener('dealmaster:operational-data-updated',refresh);window.addEventListener('dealmaster:assetguard-sla-config-updated',refresh);return()=>{window.removeEventListener('dealmaster:assetguard-connected',refresh);window.removeEventListener('dealmaster:operational-data-updated',refresh);window.removeEventListener('dealmaster:assetguard-sla-config-updated',refresh);};},[companyId,storeId,storeName]);
 return <section className="mt-6 rounded-[26px] border border-emerald-400/10 bg-emerald-400/[0.025] p-4 md:p-5"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-300"><KeyRound size={17}/></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-emerald-500/70">AssetGuard · logística</p><p className="mt-0.5 text-sm font-semibold text-white">Manuais, chaves e movimentações</p></div></div><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${connected?'bg-emerald-400':'bg-zinc-600'}`}/><button onClick={load} className="grid h-8 w-8 place-items-center rounded-full bg-white/[0.05] text-zinc-500"><RefreshCw size={14} className={loading?'animate-spin':''}/></button></div></div><div className="space-y-2">{alerts.map(alert=><AssetAlertCard key={alert.id} alert={alert}/>)}</div></section>;
};

const tones:Record<Tone,string>={critical:'border-red-500/20 bg-red-500/[0.065]',warning:'border-amber-400/20 bg-amber-400/[0.055]',good:'border-emerald-500/20 bg-emerald-500/[0.055]',info:'border-sky-400/20 bg-sky-400/[0.05]'};
const AssetAlertCard=({alert}:{alert:Alert})=><div className={`rounded-[20px] border p-4 ${tones[alert.tone]}`}><div className="flex items-start gap-3"><div className={`mt-0.5 ${alert.tone==='critical'?'text-red-300':alert.tone==='warning'?'text-amber-300':alert.tone==='good'?'text-emerald-300':'text-sky-300'}`}>{alert.tone==='critical'?<ShieldAlert size={17}/>:alert.tone==='warning'?<AlertTriangle size={17}/>:<CheckCircle2 size={17}/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><p className="font-semibold text-white">{alert.title}</p>{alert.metric&&<span className="rounded-full bg-black/20 px-2.5 py-1 text-[11px] font-semibold text-zinc-300">{alert.metric}</span>}</div><p className="mt-1.5 text-sm leading-5 text-zinc-400">{alert.text}</p></div></div></div>;
export default AssetGuardSmartAlerts;
