import React, { useMemo, useState } from 'react';
import { BookOpenCheck, ExternalLink, KeyRound, MapPin, PackageCheck, Search, ShieldCheck, X, PlusCircle } from 'lucide-react';
import { OperationalStockItem, User } from '../types';
import { storeScopedOperationalService } from '../services/storeScopedOperationalService';

const MANUAL_TRACK_URL='https://controle-manuais-chaves.vercel.app/sistema';
const MANUAL_REGISTER_URL='https://controle-manuais-chaves.vercel.app/sistema/novo';
type Props={currentUser:User;companyId:string;storeId:string;companyName:string;storeName:string;};
const AssetGuardPanel:React.FC<Props>=({currentUser,companyId,storeId,companyName,storeName})=>{
 const[open,setOpen]=useState(false);const[plate,setPlate]=useState('');const[stock,setStock]=useState<OperationalStockItem[]>([]);const[stockCount,setStockCount]=useState<number|null>(null);const[stockValue,setStockValue]=useState<number|null>(null);
 const cleanPlate=useMemo(()=>plate.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,7),[plate]);const isManager=currentUser.role==='admin'||currentUser.role==='manager';
 const loadStock=async()=>{try{const rows=await storeScopedOperationalService.getLatestStock(storeId,companyId);const valid=Array.from(new Map(rows.filter(item=>/^[A-Z0-9]{7}$/.test(String(item.plate||'').replace(/[^A-Z0-9]/g,''))).map(item=>[String(item.plate).replace(/[^A-Z0-9]/g,''),item])).values());setStock(valid);setStockCount(valid.length);setStockValue(valid.reduce((sum,item)=>sum+(Number(item.cost)||0),0));}catch{setStock([]);setStockCount(null);setStockValue(null);}};
 const openPanel=()=>{setOpen(true);loadStock();};
 const contextParams=(item?:OperationalStockItem)=>{const params=new URLSearchParams();const selectedPlate=item?.plate||cleanPlate;if(selectedPlate)params.set('plate',String(selectedPlate).toUpperCase().replace(/[^A-Z0-9]/g,''));if(item?.vehicle)params.set('model',item.vehicle);params.set('source','dealmaster');params.set('vehicleStore',storeName||'Unidade atual');params.set('company',companyName||'Empresa');return params;};
 const openManualTrack=(item?:OperationalStockItem)=>window.open(`${MANUAL_TRACK_URL}?${contextParams(item).toString()}`,'_blank','noopener,noreferrer');
 const registerAsset=(item:OperationalStockItem)=>window.open(`${MANUAL_REGISTER_URL}?${contextParams(item).toString()}`,'_blank','noopener,noreferrer');
 const money=(value:number|null)=>value===null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value);
 return <><div className="fixed bottom-56 right-3 z-[139] md:right-5"><button onClick={openPanel} title="AssetGuard" className="group flex h-12 w-12 items-center overflow-hidden rounded-full border border-emerald-400/25 bg-zinc-950/95 text-emerald-300 shadow-2xl backdrop-blur-xl transition-all duration-300 hover:w-40 hover:border-emerald-400/50 hover:bg-zinc-900"><span className="grid h-12 w-12 shrink-0 place-items-center"><KeyRound size={18}/></span><span className="hidden whitespace-nowrap pr-4 text-sm font-semibold opacity-0 transition-opacity duration-200 group-hover:opacity-100 md:block">AssetGuard</span></button></div>
 {open&&<div className="fixed inset-0 z-[250] flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false);}}><div className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-[32px] border border-white/10 bg-zinc-950 shadow-2xl"><div className="flex items-start justify-between border-b border-white/10 p-6 md:p-8"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-emerald-400"><ShieldCheck size={15}/> AssetGuard</div><h2 className="text-3xl font-semibold tracking-tight text-white">Radar de manuais e chaves.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">{companyName} · {storeName}. Estoque lido exclusivamente desta unidade.</p></div><button onClick={()=>setOpen(false)} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-white/10 bg-white/[0.04] text-zinc-400 hover:text-white"><X size={18}/></button></div>
 {isManager&&<div className="border-b border-white/10 p-6 md:p-8"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Estoque conectado</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><p className="text-2xl font-semibold text-white">{stockCount===null?'—':stockCount}</p><p className="text-xs text-zinc-500">veículo(s) válidos nesta unidade</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><p className="text-2xl font-semibold text-white">{money(stockValue)}</p><p className="text-xs text-zinc-500">capital desta unidade</p></div></div><button onClick={loadStock} className="mt-3 rounded-xl border border-white/10 px-3 py-2 text-xs text-zinc-300">Atualizar leitura</button></div>}
 {isManager&&stock.length>0&&<div className="border-b border-white/10 p-6 md:p-8"><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Cadastro rápido pelo estoque</p><p className="mt-1 text-sm text-zinc-400">Abra a ficha existente ou cadastre manual e chave levando os dados do veículo.</p></div><div className="max-h-64 space-y-2 overflow-y-auto pr-1">{stock.map(item=><div key={item.id} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[0.03] p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-mono text-sm font-semibold text-white">{item.plate}</span><span className="truncate text-sm text-zinc-400">{item.vehicle}</span></div><p className="mt-1 text-[11px] text-zinc-600">{item.stockDays} dias em estoque · {storeName}</p></div><div className="flex shrink-0 gap-2"><button onClick={()=>openManualTrack(item)} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-semibold text-zinc-300 hover:bg-white/[0.06]">Abrir ficha</button><button onClick={()=>registerAsset(item)} className="flex items-center gap-1.5 rounded-xl bg-emerald-400 px-3 py-2 text-xs font-semibold text-black hover:bg-emerald-300"><PlusCircle size={14}/> Cadastrar</button></div></div>)}</div></div>}
 <div className="grid gap-3 p-6 md:grid-cols-3 md:p-8"><Info icon={<MapPin size={18}/>} title="Veículo" text={`Local atual informado pelo DealMaster: ${storeName}.`}/><Info icon={<BookOpenCheck size={18}/>} title="Manual" text="Continua guardado na unidade de origem até ser realmente enviado."/><Info icon={<KeyRound size={18}/>} title="Chave reserva" text="Localização independente do carro, com transferência e recebimento próprios."/></div>
 <div className="border-t border-white/10 p-6 md:p-8"><label className="mb-2 block text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Localizar por placa</label><div className="flex flex-col gap-3 sm:flex-row"><div className="flex h-12 flex-1 items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] px-4"><Search size={17} className="text-zinc-500"/><input value={cleanPlate} onChange={e=>setPlate(e.target.value)} placeholder="ABC1D23" className="w-full bg-transparent font-mono text-sm uppercase text-white outline-none placeholder:text-zinc-600"/></div><button onClick={()=>openManualTrack()} className="flex h-12 items-center justify-center gap-2 rounded-2xl bg-white px-5 text-sm font-semibold text-black hover:bg-zinc-200">{cleanPlate?'Abrir veículo':'Abrir AssetGuard'} <ExternalLink size={16}/></button></div><div className="mt-3 flex items-start gap-2 rounded-2xl border border-emerald-400/10 bg-emerald-400/[0.04] p-3 text-xs leading-5 text-zinc-400"><PackageCheck size={16} className="mt-0.5 shrink-0 text-emerald-400"/><span>O carro pode estar em <strong className="text-zinc-200">{storeName}</strong> e o manual continuar corretamente em outra unidade. A movimentação só começa quando houver solicitação.</span></div></div></div></div>}</>;
};
const Info=({icon,title,text}:{icon:React.ReactNode;title:string;text:string})=><div className="rounded-[24px] border border-white/10 bg-white/[0.035] p-5"><div className="mb-4 grid h-10 w-10 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-400">{icon}</div><div className="font-semibold text-white">{title}</div><p className="mt-1 text-sm leading-5 text-zinc-500">{text}</p></div>;
export default AssetGuardPanel;