import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, Building2, CheckCircle2, Clock3, RefreshCw, TimerReset, Truck, X } from 'lucide-react';
import { AssetGuardSla, assetGuardIntegrationService } from '../services/assetGuardIntegrationService';

type Props={companyId:string;};
type Period=7|30|90;
const fmtHours=(value:number)=>{if(!Number.isFinite(value)||value<=0)return '0h';if(value<24)return `${value.toFixed(value<10?1:0)}h`;return `${(value/24).toFixed(1)}d`;};
const fmtPct=(value:number)=>`${Number(value||0).toFixed(0)}%`;
const statusLabel={waiting_send:'Aguardando envio',in_transit:'Em transporte',received:'Recebido',delivered:'Entregue'} as const;

const AssetGuardSlaPanel:React.FC<Props>=({companyId})=>{
 const[open,setOpen]=useState(false);const[period,setPeriod]=useState<Period>(30);const[data,setData]=useState<AssetGuardSla|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const load=async(nextPeriod:Period=period)=>{setLoading(true);setError('');try{const result=await assetGuardIntegrationService.getSla(companyId,nextPeriod);setData(result);}catch(e){setData(null);setError(e instanceof Error?e.message:'Não foi possível carregar o SLA do AssetGuard.');}finally{setLoading(false);}};
 const openPanel=()=>{setOpen(true);load();};
 useEffect(()=>{if(!open)return;load(period);},[period]);
 const worstUnit=useMemo(()=>data?.units?.[0]||null,[data]);
 return <>
  <button onClick={openPanel} className="flex items-center gap-2 rounded-xl border border-emerald-400/20 bg-emerald-400/[0.06] px-3 py-2 text-xs font-semibold text-emerald-300 hover:bg-emerald-400/[0.10]"><BarChart3 size={14}/> SLA logística</button>
  {open&&<div className="fixed inset-0 z-[320] overflow-y-auto bg-black/80 p-3 backdrop-blur-md md:p-6" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><div className="mx-auto max-w-6xl overflow-hidden rounded-[32px] border border-white/10 bg-zinc-950 shadow-2xl">
   <div className="flex flex-col gap-4 border-b border-white/10 p-5 md:flex-row md:items-center md:justify-between md:p-7"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-emerald-400"><Clock3 size={15}/> AssetGuard · SLA</div><h3 className="text-2xl font-semibold text-white md:text-3xl">Eficiência da logística de manuais e chaves</h3><p className="mt-2 text-sm text-zinc-500">Da solicitação ao envio, do transporte ao recebimento e até a entrega ao cliente.</p></div><div className="flex items-center gap-2"><button onClick={()=>load()} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-white/[0.04] text-zinc-400"><RefreshCw size={17} className={loading?'animate-spin':''}/></button><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-white/[0.04] text-zinc-400"><X size={18}/></button></div></div>
   <div className="p-5 md:p-7"><div className="mb-5 flex flex-wrap gap-2">{([7,30,90] as Period[]).map(value=><button key={value} onClick={()=>setPeriod(value)} className={`rounded-full px-4 py-2 text-xs font-semibold ${period===value?'bg-white text-black':'border border-white/10 bg-white/[0.03] text-zinc-400'}`}>{value} dias</button>)}</div>
    {error?<div className="rounded-2xl border border-red-400/20 bg-red-400/[0.06] p-5 text-sm text-red-200"><AlertTriangle size={18} className="mb-2"/>{error}</div>:loading&&!data?<div className="grid min-h-64 place-items-center text-zinc-500"><div className="text-center"><RefreshCw className="mx-auto mb-3 animate-spin"/><p>Calculando tempos de operação...</p></div></div>:data?<>
     <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<TimerReset size={18}/>} label="Solicitação → envio" value={fmtHours(data.summary.avgRequestToSendHours)} note={`SLA ${fmtPct(data.summary.requestSlaPercent)} · meta ${data.slaHours}h`}/><Metric icon={<Truck size={18}/>} label="Transporte → recebimento" value={fmtHours(data.summary.avgTransitHours)} note={`SLA ${fmtPct(data.summary.transitSlaPercent)} · meta ${data.slaHours}h`}/><Metric icon={<Clock3 size={18}/>} label="Solicitação → entrega" value={fmtHours(data.summary.avgTotalHours)} note={`${data.summary.delivered} entrega(s) concluída(s)`}/><Metric icon={<AlertTriangle size={18}/>} label="Fora do SLA agora" value={`${data.summary.overdue}`} note={`${data.summary.waitingSend} aguardando envio · ${data.summary.inTransit} em trânsito`} danger={data.summary.overdue>0}/></div>
     <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-[26px] border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-600">Unidades de origem</p><h4 className="mt-1 text-lg font-semibold text-white">Quem está respondendo mais rápido</h4></div><Building2 size={20} className="text-zinc-600"/></div><div className="mt-4 space-y-2">{data.units.length?data.units.map((unit,index)=><div key={`${unit.unit}-${index}`} className="grid gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 sm:grid-cols-[1.5fr_repeat(4,.7fr)] sm:items-center"><div><p className="font-semibold text-white">{unit.unit}</p><p className="mt-1 text-[11px] text-zinc-600">{unit.requests} solicitação(ões) · {unit.overdue} vencida(s)</p></div><Mini label="Envio" value={fmtHours(unit.avgRequestToSendHours)}/><Mini label="SLA envio" value={fmtPct(unit.requestSlaPercent)} good={unit.requestSlaPercent>=80}/><Mini label="Transporte" value={fmtHours(unit.avgTransitHours)}/><Mini label="SLA transp." value={fmtPct(unit.transitSlaPercent)} good={unit.transitSlaPercent>=80}/></div>):<Empty text="Ainda não há solicitações suficientes neste período."/>}</div></section>
      <section className="rounded-[26px] border border-white/10 bg-white/[0.025] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-600">Leitura executiva</p><h4 className="mt-1 text-lg font-semibold text-white">Onde agir primeiro</h4>{worstUnit?<div className="mt-5 rounded-2xl border border-amber-400/15 bg-amber-400/[0.05] p-4"><p className="text-xs text-zinc-500">Maior prioridade no período</p><p className="mt-1 text-xl font-semibold text-white">{worstUnit.unit}</p><p className="mt-2 text-sm leading-6 text-zinc-400">Tempo médio para envio: <strong className="text-zinc-200">{fmtHours(worstUnit.avgRequestToSendHours)}</strong>. Pendências fora do SLA: <strong className="text-zinc-200">{worstUnit.overdue}</strong>.</p></div>:<Empty text="Sem gargalo identificado ainda."/>}<div className="mt-3 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-400"/><p className="font-semibold text-white">Meta operacional</p></div><p className="mt-2 text-sm leading-6 text-zinc-500">Separar e iniciar o envio em até {data.slaHours}h. Confirmar o recebimento em até {data.slaHours}h após a saída.</p></div></section></div>
     <section className="mt-5 rounded-[26px] border border-white/10 bg-white/[0.025] p-5"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-600">Fluxos recentes</p><h4 className="mt-1 text-lg font-semibold text-white">Da solicitação até a entrega</h4></div><div className="mt-4 max-h-80 space-y-2 overflow-y-auto pr-1">{data.recent.length?data.recent.map((row,index)=><div key={`${row.vehicleId}-${row.requestAt}-${index}`} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-semibold text-white">{row.plate||'SEM PLACA'}</span><span className="truncate text-sm text-zinc-400">{row.model}</span>{row.overdue&&<span className="rounded-full bg-red-400/10 px-2 py-1 text-[10px] font-semibold uppercase text-red-300">SLA vencido</span>}</div><p className="mt-1 text-[11px] text-zinc-600">{row.origin} → {row.destination} · {row.items}</p></div><div className="grid shrink-0 grid-cols-3 gap-3 text-right"><Mini label="Envio" value={row.requestToSendHours===null?'—':fmtHours(row.requestToSendHours)}/><Mini label="Transporte" value={row.transitHours===null?'—':fmtHours(row.transitHours)}/><Mini label={statusLabel[row.status]} value={row.totalHours===null?'—':fmtHours(row.totalHours)}/></div></div>):<Empty text="Nenhum fluxo registrado neste período."/>}</div></section>
    </>:null}
   </div>
  </div></div>}
 </>;
};

const Metric=({icon,label,value,note,danger=false}:{icon:React.ReactNode;label:string;value:string;note:string;danger?:boolean})=><div className={`rounded-[24px] border p-5 ${danger?'border-red-400/20 bg-red-400/[0.06]':'border-white/10 bg-white/[0.03]'}`}><div className={`mb-4 grid h-10 w-10 place-items-center rounded-2xl ${danger?'bg-red-400/10 text-red-300':'bg-emerald-400/10 text-emerald-300'}`}>{icon}</div><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-2xl font-semibold text-white">{value}</p><p className="mt-2 text-[11px] leading-5 text-zinc-600">{note}</p></div>;
const Mini=({label,value,good=false}:{label:string;value:string;good?:boolean})=><div><p className="text-[10px] uppercase tracking-[0.08em] text-zinc-600">{label}</p><p className={`mt-1 text-sm font-semibold ${good?'text-emerald-300':'text-zinc-300'}`}>{value}</p></div>;
const Empty=({text}:{text:string})=><div className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-zinc-600">{text}</div>;
export default AssetGuardSlaPanel;
