import React, { useMemo, useState } from 'react';
import { BookOpenCheck, ExternalLink, KeyRound, MapPin, PackageCheck, Search, ShieldCheck, X } from 'lucide-react';
import { User } from '../types';
import { operationalDataService } from '../services/operationalDataService';

const MANUAL_TRACK_URL='https://controle-manuais-chaves.vercel.app/sistema';
type Props={currentUser:User;companyName:string;storeName:string;};
const AssetGuardPanel:React.FC<Props>=({currentUser,companyName,storeName})=>{
 const[open,setOpen]=useState(false);const[plate,setPlate]=useState('');const[stockCount,setStockCount]=useState<number|null>(null);
 const cleanPlate=useMemo(()=>plate.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,7),[plate]);const isManager=currentUser.role==='admin'||currentUser.role==='manager';
 const loadStock=async()=>{try{const stock=await operationalDataService.getLatestStock();setStockCount(stock.length);}catch{setStockCount(null);}};
 const openPanel=()=>{setOpen(true);loadStock();};
 const openManualTrack=()=>{const params=new URLSearchParams();if(cleanPlate)params.set('plate',cleanPlate);params.set('source','dealmaster');params.set('vehicleStore',storeName||'Unidade atual');params.set('company',companyName||'Empresa');window.open(`${MANUAL_TRACK_URL}?${params.toString()}`,'_blank','noopener,noreferrer');};
 return <><div className="fixed bottom-56 right-3 z-[139] md:right-5"><button onClick={openPanel} title="AssetGuard" className="group flex h-12 w-12 items-center overflow-hidden rounded-full border border-emerald-400/25 bg-zinc-950/95 text-emerald-300 shadow-2xl backdrop-blur-xl transition-all duration-300 hover:w-40 hover:border-emerald-400/50 hover:bg-zinc-900"><span className="grid h-12 w-12 shrink-0 place-items-center"><KeyRound size={18}/></span><span className="hidden whitespace-nowrap pr-4 text-sm font-semibold opacity-0 transition-opacity duration-200 group-hover:opacity-100 md:block">AssetGuard</span></button></div>
 {open&&<div className="fixed inset-0 z-[250] flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false);}}><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-[32px] border border-white/10 bg-zinc-950 shadow-2xl"><div className="flex items-start justify-between border-b border-white/10 p-6 md:p-8"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-emerald-400"><ShieldCheck size={15}/> AssetGuard</div><h2 className="text-3xl font-semibold tracking-tight text-white">Radar de manuais e chaves.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">{companyName} · {storeName}. O DealMaster envia o contexto do veículo e o AssetGuard mantém a custódia física dos itens.</p></div><button onClick={()=>setOpen(false)} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-white/10 bg-white/[0.04] text-zinc-400 hover:text-white"><X size={18}/></button></div>
 {isManager&&<div className="border-b border-white/10 p-6 md:p-8"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Estoque conectado</p><div className="mt-3 flex items-center justify-between rounded-2xl border border-white/10 bg-white/[0.035] p-4"><div><p className="text-2xl font-semibold text-white">{stockCount===null?'—':stockCount}</p><p className="text-xs text-zinc-500">veículo(s) válidos no estoque mais recente</p></div><button onClick={loadStock} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-zinc-300">Atualizar</button></div><p className="mt-3 text-xs leading-5 text-zinc-500">A leitura detalhada de solicitações e transporte fica no AssetGuard. Isso evita bloqueio de navegador entre os dois domínios e mantém cada módulo com sua própria sessão.</p></div>}
 <div className="grid gap-3 p-6 md:grid-cols-3 md:p-8"><Info icon={<MapPin size={18}/>} title="Veículo" text={`Local atual informado pelo DealMaster: ${storeName}.`}/><Info icon={<BookOpenCheck size={18}/>} title="Manual" text="Continua guardado na unidade de origem até ser realmente enviado."/><Info icon={<KeyRound size={18}/>} title="Chave reserva" text="Localização independente do carro, com transferência e recebimento próprios."/></div>
 <div className="border-t border-white/10 p-6 md:p-8"><label className="mb-2 block text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Localizar por placa</label><div className="flex flex-col gap-3 sm:flex-row"><div className="flex h-12 flex-1 items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] px-4"><Search size={17} className="text-zinc-500"/><input value={cleanPlate} onChange={e=>setPlate(e.target.value)} placeholder="ABC1D23" className="w-full bg-transparent font-mono text-sm uppercase text-white outline-none placeholder:text-zinc-600"/></div><button onClick={openManualTrack} className="flex h-12 items-center justify-center gap-2 rounded-2xl bg-white px-5 text-sm font-semibold text-black hover:bg-zinc-200">{cleanPlate?'Abrir veículo':'Abrir AssetGuard'} <ExternalLink size={16}/></button></div><div className="mt-3 flex items-start gap-2 rounded-2xl border border-emerald-400/10 bg-emerald-400/[0.04] p-3 text-xs leading-5 text-zinc-400"><PackageCheck size={16} className="mt-0.5 shrink-0 text-emerald-400"/><span>O carro pode estar em <strong className="text-zinc-200">{storeName}</strong> e o manual continuar corretamente em outra unidade. A movimentação só começa quando houver solicitação.</span></div></div></div></div>}</>;
};
const Info=({icon,title,text}:{icon:React.ReactNode;title:string;text:string})=><div className="rounded-[24px] border border-white/10 bg-white/[0.035] p-5"><div className="mb-4 grid h-10 w-10 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-400">{icon}</div><div className="font-semibold text-white">{title}</div><p className="mt-1 text-sm leading-5 text-zinc-500">{text}</p></div>;
export default AssetGuardPanel;