import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, Building2, CheckCircle2, Clock3, RefreshCw, RotateCcw, Save, Settings2, TimerReset, Truck, X } from 'lucide-react';
import { AssetGuardSla, AssetGuardSlaUnit, assetGuardIntegrationService } from '../services/assetGuardIntegrationService';
import { AssetGuardSlaResolvedConfig, AssetGuardSlaThresholds, DEFAULT_ASSETGUARD_SLA, assetGuardSlaConfigService } from '../services/assetGuardSlaConfigService';

type Props={companyId:string;storeId:string;storeName:string;canManageCompany:boolean;};
type Period=7|30|90;
type Signal='green'|'amber'|'red';
const fmtHours=(value:number)=>{if(!Number.isFinite(value)||value<=0)return '0h';if(value<24)return `${value.toFixed(value<10?1:0)}h`;return `${(value/24).toFixed(1)}d`;};
const fmtPct=(value:number)=>`${Number(value||0).toFixed(0)}%`;
const statusLabel={waiting_send:'Aguardando envio',in_transit:'Em transporte',received:'Recebido',delivered:'Entregue'} as const;
const sourceLabel={default:'Padrão do sistema',company:'Padrão da empresa',store:'Regra desta unidade'} as const;
const signalClasses:Record<Signal,string>={green:'border-emerald-400/20 bg-emerald-400/[0.055]',amber:'border-amber-400/20 bg-amber-400/[0.055]',red:'border-red-400/20 bg-red-400/[0.06]'};
const dotClasses:Record<Signal,string>={green:'bg-emerald-400',amber:'bg-amber-400',red:'bg-red-400'};

const validate=(value:AssetGuardSlaThresholds)=>{
 if(value.sendTargetHours<=0||value.transitTargetHours<=0)throw new Error('As metas precisam ser maiores que zero.');
 if(value.sendCriticalHours<value.sendTargetHours)throw new Error('O limite crítico de envio não pode ser menor que a meta.');
 if(value.transitCriticalHours<value.transitTargetHours)throw new Error('O limite crítico de transporte não pode ser menor que a meta.');
 return value;
};
const signalForValue=(value:number,target:number,critical:number):Signal=>value>critical?'red':value>target?'amber':'green';
const unitSignal=(unit:AssetGuardSlaUnit,thresholds:AssetGuardSlaThresholds):Signal=>{
 if(unit.overdue>0||unit.avgRequestToSendHours>thresholds.sendCriticalHours||unit.avgTransitHours>thresholds.transitCriticalHours)return 'red';
 if(unit.waitingSend>0||unit.inTransit>0||unit.avgRequestToSendHours>thresholds.sendTargetHours||unit.avgTransitHours>thresholds.transitTargetHours)return 'amber';
 return 'green';
};

const AssetGuardSlaPanel:React.FC<Props>=({companyId,storeId,storeName,canManageCompany})=>{
 const[open,setOpen]=useState(false);const[period,setPeriod]=useState<Period>(30);const[data,setData]=useState<AssetGuardSla|null>(null);const[config,setConfig]=useState<AssetGuardSlaResolvedConfig|null>(null);const[draft,setDraft]=useState<AssetGuardSlaThresholds>(DEFAULT_ASSETGUARD_SLA);const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[configOpen,setConfigOpen]=useState(false);const[message,setMessage]=useState('');
 const load=async(nextPeriod:Period=period)=>{setLoading(true);setError('');try{const resolved=await assetGuardSlaConfigService.get(companyId,storeId);setConfig(resolved);setDraft({sendTargetHours:resolved.sendTargetHours,sendCriticalHours:resolved.sendCriticalHours,transitTargetHours:resolved.transitTargetHours,transitCriticalHours:resolved.transitCriticalHours});const result=await assetGuardIntegrationService.getSla(companyId,nextPeriod,resolved);setData(result);}catch(e){setData(null);setError(e instanceof Error?e.message:'Não foi possível carregar o SLA do AssetGuard.');}finally{setLoading(false);}};
 useEffect(()=>{if(open)load(period);},[open,period,companyId,storeId]);
 useEffect(()=>{const refresh=()=>{if(open)load(period);};window.addEventListener('dealmaster:assetguard-sla-config-updated',refresh);return()=>window.removeEventListener('dealmaster:assetguard-sla-config-updated',refresh);},[open,period,companyId,storeId]);
 const worstUnit=useMemo(()=>data?.units?.[0]||null,[data]);
 const thresholds=data?.thresholds||config||DEFAULT_ASSETGUARD_SLA;
 const updateDraft=(key:keyof AssetGuardSlaThresholds,value:string)=>setDraft(current=>({...current,[key]:Math.max(Number(value)||0,0)}));
 const saveStore=async()=>{setSaving(true);setMessage('');try{validate(draft);await assetGuardSlaConfigService.saveStore(companyId,storeId,draft);setMessage(`Meta salva para ${storeName}.`);setConfigOpen(false);}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setSaving(false);}};
 const saveCompany=async()=>{setSaving(true);setMessage('');try{validate(draft);await assetGuardSlaConfigService.saveCompany(companyId,draft);setMessage(config?.source==='store'?'Padrão da empresa salvo. Esta unidade continua usando sua regra própria.':'Padrão da empresa atualizado.');}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setSaving(false);}};
 const useCompany=async()=>{setSaving(true);setMessage('');try{await assetGuardSlaConfigService.useCompanyDefault(companyId,storeId);setMessage(`${storeName} voltou a seguir o padrão da empresa.`);setConfigOpen(false);}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível restaurar o padrão.');}finally{setSaving(false);}};
 return <>
  <button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl border border-emerald-400/20 bg-emerald-400/[0.06] px-3 py-2 text-xs font-semibold text-emerald-300 hover:bg-emerald-400/[0.10]"><BarChart3 size={14}/> SLA logística</button>
  {open&&<div className="fixed inset-0 z-[320] overflow-y-auto bg-black/80 p-3 backdrop-blur-md md:p-6" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><div className="mx-auto max-w-6xl overflow-hidden rounded-[32px] border border-white/10 bg-zinc-950 shadow-2xl">
   <div className="flex flex-col gap-4 border-b border-white/10 p-5 md:flex-row md:items-center md:justify-between md:p-7"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-emerald-400"><Clock3 size={15}/> AssetGuard · SLA</div><h3 className="text-2xl font-semibold text-white md:text-3xl">Eficiência da logística de manuais e chaves</h3><p className="mt-2 text-sm text-zinc-500">Da solicitação ao envio, do transporte ao recebimento e até a entrega ao cliente.</p></div><div className="flex items-center gap-2"><button onClick={()=>setConfigOpen(value=>!value)} title="Configurar metas" className={`grid h-10 w-10 place-items-center rounded-full border ${configOpen?'border-emerald-400/30 bg-emerald-400/10 text-emerald-300':'border-white/10 bg-white/[0.04] text-zinc-400'}`}><Settings2 size={17}/></button><button onClick={()=>load()} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-white/[0.04] text-zinc-400"><RefreshCw size={17} className={loading?'animate-spin':''}/></button><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-white/[0.04] text-zinc-400"><X size={18}/></button></div></div>
   <div className="p-5 md:p-7"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{([7,30,90] as Period[]).map(value=><button key={value} onClick={()=>setPeriod(value)} className={`rounded-full px-4 py-2 text-xs font-semibold ${period===value?'bg-white text-black':'border border-white/10 bg-white/[0.03] text-zinc-400'}`}>{value} dias</button>)}</div>{config&&<div className="flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-3 py-2 text-[11px] text-zinc-400"><span className={`h-2 w-2 rounded-full ${config.source==='store'?'bg-sky-400':config.source==='company'?'bg-violet-400':'bg-zinc-500'}`}/>{sourceLabel[config.source]}</div>}</div>
    {configOpen&&<section className="mb-5 rounded-[24px] border border-emerald-400/15 bg-emerald-400/[0.035] p-5"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-emerald-400">Metas de SLA</p><h4 className="mt-1 text-lg font-semibold text-white">Defina quando fica verde, amarelo ou vermelho</h4><p className="mt-1 text-sm text-zinc-500">A regra da unidade prevalece sobre o padrão da empresa.</p></div><div className="flex gap-3 text-[11px]"><Legend tone="green" text="Dentro da meta"/><Legend tone="amber" text="Atenção"/><Legend tone="red" text="Crítico"/></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><ThresholdGroup title="Solicitação → envio" target={draft.sendTargetHours} critical={draft.sendCriticalHours} onTarget={value=>updateDraft('sendTargetHours',value)} onCritical={value=>updateDraft('sendCriticalHours',value)}/><ThresholdGroup title="Transporte → recebimento" target={draft.transitTargetHours} critical={draft.transitCriticalHours} onTarget={value=>updateDraft('transitTargetHours',value)} onCritical={value=>updateDraft('transitCriticalHours',value)}/></div><div className="mt-5 flex flex-wrap items-center gap-2"><button disabled={saving} onClick={saveStore} className="flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black disabled:opacity-50"><Save size={14}/> Salvar nesta unidade</button>{canManageCompany&&<button disabled={saving} onClick={saveCompany} className="flex items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-400/[0.06] px-4 py-2.5 text-xs font-semibold text-violet-200 disabled:opacity-50"><Save size={14}/> Salvar padrão da empresa</button>}{config?.source==='store'&&<button disabled={saving} onClick={useCompany} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-xs font-semibold text-zinc-400 disabled:opacity-50"><RotateCcw size={14}/> Usar padrão da empresa</button>}<span className="text-[11px] text-zinc-600">Verde ≤ meta · amarelo até o limite crítico · vermelho acima dele</span></div></section>}
    {message&&<div className="mb-5 rounded-2xl border border-white/10 bg-white/[0.035] px-4 py-3 text-xs text-zinc-300">{message}</div>}
    {error?<div className="rounded-2xl border border-red-400/20 bg-red-400/[0.06] p-5 text-sm text-red-200"><AlertTriangle size={18} className="mb-2"/>{error}</div>:loading&&!data?<div className="grid min-h-64 place-items-center text-zinc-500"><div className="text-center"><RefreshCw className="mx-auto mb-3 animate-spin"/><p>Calculando tempos de operação...</p></div></div>:data?<>
     <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<TimerReset size={18}/>} label="Solicitação → envio" value={fmtHours(data.summary.avgRequestToSendHours)} note={`Dentro da meta: ${fmtPct(data.summary.requestSlaPercent)} · verde até ${thresholds.sendTargetHours}h`} signal={signalForValue(data.summary.avgRequestToSendHours,thresholds.sendTargetHours,thresholds.sendCriticalHours)}/><Metric icon={<Truck size={18}/>} label="Transporte → recebimento" value={fmtHours(data.summary.avgTransitHours)} note={`Dentro da meta: ${fmtPct(data.summary.transitSlaPercent)} · verde até ${thresholds.transitTargetHours}h`} signal={signalForValue(data.summary.avgTransitHours,thresholds.transitTargetHours,thresholds.transitCriticalHours)}/><Metric icon={<Clock3 size={18}/>} label="Solicitação → entrega" value={fmtHours(data.summary.avgTotalHours)} note={`${data.summary.delivered} entrega(s) concluída(s)`}/><Metric icon={<AlertTriangle size={18}/>} label="Críticos agora" value={`${data.summary.overdue}`} note={`${data.summary.waitingSend} aguardando envio · ${data.summary.inTransit} em trânsito`} signal={data.summary.overdue>0?'red':'green'}/></div>
     <div className="mt-4 flex flex-wrap gap-2"><Legend tone="green" text={`Envio ≤ ${thresholds.sendTargetHours}h · transporte ≤ ${thresholds.transitTargetHours}h`}/><Legend tone="amber" text={`Atenção até ${Math.max(thresholds.sendCriticalHours,thresholds.transitCriticalHours)}h`}/><Legend tone="red" text="Acima do limite crítico"/></div>
     <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-[26px] border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-600">Unidades de origem</p><h4 className="mt-1 text-lg font-semibold text-white">Ranking com semáforo operacional</h4></div><Building2 size={20} className="text-zinc-600"/></div><div className="mt-4 space-y-2">{data.units.length?data.units.map((unit,index)=>{const signal=unitSignal(unit,thresholds);return <div key={`${unit.unit}-${index}`} className={`grid gap-3 rounded-2xl border p-4 sm:grid-cols-[1.5fr_repeat(4,.7fr)] sm:items-center ${signalClasses[signal]}`}><div><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${dotClasses[signal]}`}/><p className="font-semibold text-white">{unit.unit}</p></div><p className="mt-1 text-[11px] text-zinc-500">{unit.requests} solicitação(ões) · {unit.waitingSend} aguardando · {unit.inTransit} em trânsito · {unit.overdue} crítica(s)</p></div><Mini label="Envio" value={fmtHours(unit.avgRequestToSendHours)} signal={signalForValue(unit.avgRequestToSendHours,thresholds.sendTargetHours,thresholds.sendCriticalHours)}/><Mini label="Dentro meta" value={fmtPct(unit.requestSlaPercent)} signal={unit.requestSlaPercent>=80?'green':unit.requestSlaPercent>=50?'amber':'red'}/><Mini label="Transporte" value={fmtHours(unit.avgTransitHours)} signal={signalForValue(unit.avgTransitHours,thresholds.transitTargetHours,thresholds.transitCriticalHours)}/><Mini label="Dentro meta" value={fmtPct(unit.transitSlaPercent)} signal={unit.transitSlaPercent>=80?'green':unit.transitSlaPercent>=50?'amber':'red'}/></div>}):<Empty text="Ainda não há solicitações suficientes neste período."/>}</div></section>
      <section className="rounded-[26px] border border-white/10 bg-white/[0.025] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-600">Leitura executiva</p><h4 className="mt-1 text-lg font-semibold text-white">Onde agir primeiro</h4>{worstUnit?<div className={`mt-5 rounded-2xl border p-4 ${signalClasses[unitSignal(worstUnit,thresholds)]}`}><p className="text-xs text-zinc-500">Maior prioridade no período</p><div className="mt-1 flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${dotClasses[unitSignal(worstUnit,thresholds)]}`}/><p className="text-xl font-semibold text-white">{worstUnit.unit}</p></div><p className="mt-2 text-sm leading-6 text-zinc-400">Tempo médio para envio: <strong className="text-zinc-200">{fmtHours(worstUnit.avgRequestToSendHours)}</strong>. Pendências críticas: <strong className="text-zinc-200">{worstUnit.overdue}</strong>.</p></div>:<Empty text="Sem gargalo identificado ainda."/>}<div className="mt-3 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-400"/><p className="font-semibold text-white">Regra ativa</p></div><p className="mt-2 text-sm leading-6 text-zinc-500">Envio: verde até {thresholds.sendTargetHours}h e crítico acima de {thresholds.sendCriticalHours}h. Transporte: verde até {thresholds.transitTargetHours}h e crítico acima de {thresholds.transitCriticalHours}h.</p></div></section></div>
     <section className="mt-5 rounded-[26px] border border-white/10 bg-white/[0.025] p-5"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-600">Fluxos recentes</p><h4 className="mt-1 text-lg font-semibold text-white">Da solicitação até a entrega</h4></div><div className="mt-4 max-h-80 space-y-2 overflow-y-auto pr-1">{data.recent.length?data.recent.map((row,index)=><div key={`${row.vehicleId}-${row.requestAt}-${index}`} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-semibold text-white">{row.plate||'SEM PLACA'}</span><span className="truncate text-sm text-zinc-400">{row.model}</span>{row.overdue&&<span className="rounded-full bg-red-400/10 px-2 py-1 text-[10px] font-semibold uppercase text-red-300">Crítico</span>}</div><p className="mt-1 text-[11px] text-zinc-600">{row.origin} → {row.destination} · {row.items}</p></div><div className="grid shrink-0 grid-cols-3 gap-3 text-right"><Mini label="Envio" value={row.requestToSendHours===null?'—':fmtHours(row.requestToSendHours)} signal={row.requestToSendHours===null?undefined:signalForValue(row.requestToSendHours,thresholds.sendTargetHours,thresholds.sendCriticalHours)}/><Mini label="Transporte" value={row.transitHours===null?'—':fmtHours(row.transitHours)} signal={row.transitHours===null?undefined:signalForValue(row.transitHours,thresholds.transitTargetHours,thresholds.transitCriticalHours)}/><Mini label={statusLabel[row.status]} value={row.totalHours===null?'—':fmtHours(row.totalHours)}/></div></div>):<Empty text="Nenhum fluxo registrado neste período."/>}</div></section>
    </>:null}
   </div>
  </div></div>}
 </>;
};

const Metric=({icon,label,value,note,signal}:{icon:React.ReactNode;label:string;value:string;note:string;signal?:Signal})=><div className={`rounded-[24px] border p-5 ${signal?signalClasses[signal]:'border-white/10 bg-white/[0.03]'}`}><div className="mb-4 grid h-10 w-10 place-items-center rounded-2xl bg-black/20 text-zinc-300">{icon}</div><p className="text-xs text-zinc-500">{label}</p><div className="mt-1 flex items-center gap-2">{signal&&<span className={`h-2.5 w-2.5 rounded-full ${dotClasses[signal]}`}/>}<p className="text-2xl font-semibold text-white">{value}</p></div><p className="mt-2 text-[11px] leading-5 text-zinc-500">{note}</p></div>;
const Mini=({label,value,signal}:{label:string;value:string;signal?:Signal})=><div><p className="text-[10px] uppercase tracking-[0.08em] text-zinc-600">{label}</p><div className="mt-1 flex items-center gap-1.5"><span className={signal?`h-1.5 w-1.5 rounded-full ${dotClasses[signal]}`:'hidden'}/><p className={`text-sm font-semibold ${signal==='green'?'text-emerald-300':signal==='amber'?'text-amber-300':signal==='red'?'text-red-300':'text-zinc-300'}`}>{value}</p></div></div>;
const Legend=({tone,text}:{tone:Signal;text:string})=><span className="flex items-center gap-1.5 rounded-full border border-white/10 bg-black/20 px-2.5 py-1.5 text-[10px] text-zinc-400"><span className={`h-2 w-2 rounded-full ${dotClasses[tone]}`}/>{text}</span>;
const ThresholdGroup=({title,target,critical,onTarget,onCritical}:{title:string;target:number;critical:number;onTarget:(value:string)=>void;onCritical:(value:string)=>void})=><div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-sm font-semibold text-white">{title}</p><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-[11px] text-zinc-500"><span className="mb-1.5 flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Verde até</span><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-zinc-950 px-3"><input type="number" min="1" max="168" value={target} onChange={e=>onTarget(e.target.value)} className="h-10 w-full bg-transparent text-sm font-semibold text-white outline-none"/><span>h</span></div></label><label className="text-[11px] text-zinc-500"><span className="mb-1.5 flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-red-400"/>Crítico acima de</span><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-zinc-950 px-3"><input type="number" min="1" max="168" value={critical} onChange={e=>onCritical(e.target.value)} className="h-10 w-full bg-transparent text-sm font-semibold text-white outline-none"/><span>h</span></div></label></div></div>;
const Empty=({text}:{text:string})=><div className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-zinc-600">{text}</div>;
export default AssetGuardSlaPanel;
