import React, { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertCircle, ArrowRight, BrainCircuit, Calculator as CalcIcon, CalendarDays, CarFront, CheckCircle2, ChevronRight, Clock3, Coins, Gauge, Percent, Settings2, Sparkles, Target, TrendingUp, Trophy, Users, X } from 'lucide-react';
import { eachDayOfInterval, endOfMonth, format, isAfter, isBefore, isSameDay, parseISO, startOfMonth } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { doc, onSnapshot, setDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { SavedCalculation, User, CommissionConfig } from '../types';
import { formatCurrency } from '../utils/currency';
import { calculateCommission } from '../utils/commission';

interface DashboardProps { history: SavedCalculation[]; users: User[]; currentUser: User; commissionConfig: CommissionConfig | null; onStartNewCalculation: () => void; onDelete?: (id: string) => void; }
interface PerformanceConfig { monthlyGoal: number; firstHalfPercent: number; captureGoal: number; healthyMargin: number; sellerMonthlyGoal: number; sellerFirstHalfGoal: number; sellerCaptureGoal: number; holidays: string[]; }
const DEFAULT_PERFORMANCE: PerformanceConfig = { monthlyGoal: 70, firstHalfPercent: 40, captureGoal: 60, healthyMargin: 8, sellerMonthlyGoal: 15, sellerFirstHalfGoal: 6, sellerCaptureGoal: 60, holidays: [] };
const isWorkingDay = (date: Date, holidays: string[]) => date.getDay() !== 0 && !holidays.includes(format(date, 'yyyy-MM-dd'));
const effectiveProfit = (deal: SavedCalculation) => deal.data.closingType === 'banking' ? deal.summary.profit + (Number(deal.data.bankReturn) || 0) : deal.summary.profit;
const effectiveMargin = (deal: SavedCalculation) => { const invoice = Number(deal.data.invoiceValue) || 0; return invoice ? (effectiveProfit(deal) / invoice) * 100 : Number(deal.summary.marginPercent) || 0; };

const Dashboard: React.FC<DashboardProps> = ({ history, users, currentUser, commissionConfig, onStartNewCalculation }) => {
  const [selectedMonth, setSelectedMonth] = useState(() => format(new Date(), 'yyyy-MM'));
  const [selectedSeller, setSelectedSeller] = useState('all');
  const [performance, setPerformance] = useState<PerformanceConfig>(DEFAULT_PERFORMANCE);
  const [draftPerformance, setDraftPerformance] = useState<PerformanceConfig>(DEFAULT_PERFORMANCE);
  const [showPerformanceSettings, setShowPerformanceSettings] = useState(false);
  const [holidayDraft, setHolidayDraft] = useState('');
  const [isSavingPerformance, setIsSavingPerformance] = useState(false);
  const [stockFilter, setStockFilter] = useState('all');

  useEffect(() => onSnapshot(doc(db, 'config/performance'), snapshot => { if (!snapshot.exists()) return; const data = snapshot.data() as Partial<PerformanceConfig>; const merged = { ...DEFAULT_PERFORMANCE, ...data, holidays: Array.isArray(data.holidays) ? data.holidays : [] }; setPerformance(merged); setDraftPerformance(merged); setHolidayDraft(merged.holidays.join(', ')); }), []);
  const savePerformance = async () => { setIsSavingPerformance(true); try { const holidays = holidayDraft.split(',').map(v => v.trim()).filter(v => /^\d{4}-\d{2}-\d{2}$/.test(v)); const next = { ...draftPerformance, holidays }; await setDoc(doc(db, 'config/performance'), next, { merge: true }); setPerformance(next); setShowPerformanceSettings(false); } finally { setIsSavingPerformance(false); } };
  const availableMonths = useMemo(() => { const months = new Set<string>([format(new Date(), 'yyyy-MM')]); history.forEach(i => i.timestamp && months.add(i.timestamp.substring(0, 7))); return Array.from(months).filter(Boolean).sort((a,b) => b.localeCompare(a)); }, [history]);
  const availableSellers = useMemo(() => { const map = new Map<string,string>(); users.filter(u => u.status === 'active').forEach(u => map.set(u.id,u.name)); history.forEach(i => i.userId && i.userName && map.set(i.userId,i.userName)); return Array.from(map.entries()).map(([id,name]) => ({id,name})).sort((a,b) => a.name.localeCompare(b.name)); }, [history,users]);
  const formatMonth = (month:string) => { if (month === 'all') return 'Todo período'; const [y,m] = month.split('-'); const label = format(new Date(Number(y),Number(m)-1,1),'MMMM yyyy',{locale:ptBR}); return label.charAt(0).toUpperCase()+label.slice(1); };
  const monthHistory = useMemo(() => selectedMonth === 'all' ? history : history.filter(i => i.timestamp.startsWith(selectedMonth)), [history,selectedMonth]);
  const filtered = useMemo(() => selectedSeller === 'all' ? monthHistory : monthHistory.filter(i => i.userId === selectedSeller), [monthHistory,selectedSeller]);
  const closedDeals = useMemo(() => filtered.filter(i => i.data.dealStatus === 'closed'), [filtered]);
  const openDeals = useMemo(() => filtered.filter(i => i.data.dealStatus !== 'closed'), [filtered]);
  const monthTiming = useMemo(() => { if (selectedMonth === 'all') return null; const [year,month] = selectedMonth.split('-').map(Number); const start = new Date(year,month-1,1); const end = endOfMonth(start); const now = new Date(); const current = now.getFullYear()===year && now.getMonth()===month-1; const past = isBefore(end,startOfMonth(now)); const referenceDate = current ? now : past ? end : start; const workDays = eachDayOfInterval({start,end}).filter(d => isWorkingDay(d,performance.holidays)); const elapsed = workDays.filter(d => !isAfter(d,referenceDate)); const remaining = workDays.filter(d => isAfter(d,referenceDate)); const firstHalfEnd = new Date(year,month-1,15,23,59,59); const firstHalfWorkDays = workDays.filter(d => !isAfter(d,firstHalfEnd)); const firstHalfElapsed = firstHalfWorkDays.filter(d => !isAfter(d,referenceDate)); return {start,end,workDays,elapsed,remaining,firstHalfWorkDays,firstHalfElapsed,isPastMonth:past}; }, [selectedMonth,performance.holidays]);
  const meter = useMemo(() => { if(!monthTiming) return {expectedToday:0,projection:closedDeals.length,dailyNeeded:0,remainingWorkingDays:0,workingDays:0,firstHalfGoal:0,firstHalfActual:0,firstHalfExpected:0}; const total=Math.max(monthTiming.workDays.length,1), elapsed=Math.max(monthTiming.elapsed.length,1); const expectedToday=monthTiming.isPastMonth?performance.monthlyGoal:(performance.monthlyGoal*elapsed)/total; const projection=Math.round((closedDeals.length/elapsed)*total); const remainingGoal=Math.max(performance.monthlyGoal-closedDeals.length,0); const dailyNeeded=monthTiming.remaining.length?remainingGoal/monthTiming.remaining.length:remainingGoal; const firstHalfGoal=Math.ceil((performance.monthlyGoal*performance.firstHalfPercent)/100); const firstHalfActual=closedDeals.filter(d=>parseISO(d.timestamp).getDate()<=15).length; const firstHalfExpected=monthTiming.firstHalfWorkDays.length?(firstHalfGoal*monthTiming.firstHalfElapsed.length)/monthTiming.firstHalfWorkDays.length:0; return {expectedToday,projection,dailyNeeded,remainingWorkingDays:monthTiming.remaining.length,workingDays:monthTiming.workDays.length,firstHalfGoal,firstHalfActual,firstHalfExpected}; }, [closedDeals,monthTiming,performance]);
  const stats = useMemo(() => { const totalProfit=closedDeals.reduce((s,d)=>s+effectiveProfit(d),0); const avgMargin=closedDeals.length?closedDeals.reduce((s,d)=>s+effectiveMargin(d),0)/closedDeals.length:0; const captured=closedDeals.filter(d=>Number(d.data.payments?.tradeIn)>0).length; const captureRate=closedDeals.length?(captured/closedDeals.length)*100:0; const totalCommission=closedDeals.reduce((s,d)=>!commissionConfig||d.userId!==currentUser.id?s:s+calculateCommission(d.data,effectiveProfit(d),commissionConfig).total,0); return {totalProfit,avgMargin,captureRate,totalCommission}; }, [closedDeals,commissionConfig,currentUser.id]);
  const sellerPerformance = useMemo(() => { const elapsed=Math.max(monthTiming?.elapsed.length||1,1), total=Math.max(monthTiming?.workDays.length||elapsed,1), remaining=monthTiming?.remaining.length||0; return availableSellers.map(seller => { const deals=monthHistory.filter(i=>i.userId===seller.id&&i.data.dealStatus==='closed'); const count=deals.length, firstHalf=deals.filter(d=>parseISO(d.timestamp).getDate()<=15).length, captured=deals.filter(d=>Number(d.data.payments?.tradeIn)>0).length; const capture=count?(captured/count)*100:0, margin=count?deals.reduce((s,d)=>s+effectiveMargin(d),0)/count:0, profit=deals.reduce((s,d)=>s+effectiveProfit(d),0); const projection=selectedMonth==='all'?count:Math.round((count/elapsed)*total), expected=selectedMonth==='all'?0:(performance.sellerMonthlyGoal*elapsed)/total, missing=Math.max(performance.sellerMonthlyGoal-count,0), dailyNeeded=remaining?missing/remaining:missing; let diagnosis='Sem vendas fechadas no período.', tone:'good'|'warning'|'neutral'='neutral'; if(count>0){ if(projection<performance.sellerMonthlyGoal){diagnosis=`Projeção de ${projection}. Precisa de ${dailyNeeded.toFixed(1)} carro(s)/dia restante.`;tone='warning';} else if(capture<performance.sellerCaptureGoal){diagnosis=`Ritmo saudável, mas captura em ${capture.toFixed(0)}%.`;tone='warning';} else if(margin<performance.healthyMargin){diagnosis=`Volume em linha. Proteja margem, hoje em ${margin.toFixed(1)}%.`;tone='warning';} else {diagnosis=`Operação saudável. Projeção ${projection}, captura ${capture.toFixed(0)}% e margem ${margin.toFixed(1)}%.`;tone='good';}} return {...seller,count,firstHalf,capture,margin,profit,projection,expected,missing,dailyNeeded,diagnosis,tone}; }).sort((a,b)=>b.count-a.count||b.profit-a.profit); }, [availableSellers,monthHistory,monthTiming,selectedMonth,performance]);
  const selectedSellerCard = selectedSeller==='all'?null:sellerPerformance.find(i=>i.id===selectedSeller)||null;
  const chartData = useMemo(() => { if(selectedMonth==='all') return availableMonths.slice().reverse().map(month=>{let deals=history.filter(i=>i.timestamp.startsWith(month));if(selectedSeller!=='all')deals=deals.filter(i=>i.userId===selectedSeller);return{label:formatMonth(month).split(' ')[0].slice(0,3),vendas:deals.filter(i=>i.data.dealStatus==='closed').length,esperado:undefined};}); if(!monthTiming)return[]; const index=new Map(monthTiming.workDays.map((d,i)=>[format(d,'yyyy-MM-dd'),i+1]));let cumulative=0;return eachDayOfInterval({start:monthTiming.start,end:monthTiming.end}).map(day=>{cumulative+=filtered.filter(i=>isSameDay(parseISO(i.timestamp),day)&&i.data.dealStatus==='closed').length;const n=index.get(format(day,'yyyy-MM-dd'));const goal=selectedSeller==='all'?performance.monthlyGoal:performance.sellerMonthlyGoal;return{label:format(day,'dd'),vendas:cumulative,esperado:n?(goal*n)/Math.max(monthTiming.workDays.length,1):undefined};}); }, [availableMonths,filtered,history,selectedMonth,selectedSeller,monthTiming,performance]);

  const stock = useMemo(() => { let data=history.filter(i=>i.data.dealStatus!=='closed'); if(selectedSeller!=='all')data=data.filter(i=>i.userId===selectedSeller); return data.map(item=>{const days=Number(item.data.stockDays)||0,cost=Number(item.data.vehicleCost)||0,fipe=Number(item.data.fipeValue)||0,invoice=Number(item.data.invoiceValue)||0; const band=days<=30?'0-30':days<=60?'31-60':days<=90?'61-90':days<=120?'91-120':'120+'; let priority:'healthy'|'attention'|'high'|'critical'='healthy', action='Estoque novo. Preserve preço e margem.'; if(days>120){priority='critical';action='Ação imediata: revisar preço, margem e campanha para giro.';}else if(days>90){priority='critical';action='Prioridade alta: buscar proposta e flexibilizar com margem controlada.';}else if(days>60){priority='high';action='Acelerar giro: revisar anúncio e trabalhar clientes aderentes.';}else if(days>30){priority='attention';action='Acompanhar conversão e preparar ação antes dos 60 dias.';} return{...item,days,cost,fipe,invoice,band,priority,action};}).sort((a,b)=>b.days-a.days); }, [history,selectedSeller]);
  const stockBands = useMemo(() => ['0-30','31-60','61-90','91-120','120+'].map(band=>{const items=stock.filter(i=>i.band===band);return{band,count:items.length,value:items.reduce((s,i)=>s+i.cost,0)};}),[stock]);
  const stockValue=stock.reduce((s,i)=>s+i.cost,0), agedValue=stock.filter(i=>i.days>60).reduce((s,i)=>s+i.cost,0), agedCount=stock.filter(i=>i.days>60).length, criticalCount=stock.filter(i=>i.days>90).length, avgStockDays=stock.length?stock.reduce((s,i)=>s+i.days,0)/stock.length:0;
  const filteredStock=stockFilter==='all'?stock:stock.filter(i=>i.band===stockFilter);
  const stockInsight = useMemo(()=>{if(!stock.length)return{tone:'good' as const,title:'Nenhum estoque aberto registrado',text:'Quando houver veículos em negociação, o DealMaster vai distribuir o capital por idade e indicar prioridades.'};if(criticalCount>0)return{tone:'warning' as const,title:`${criticalCount} veículo(s) acima de 90 dias`,text:`Há ${formatCurrency(stock.filter(i=>i.days>90).reduce((s,i)=>s+i.cost,0))} de capital nessa faixa. Comece pelos mais antigos e revise preço, margem e exposição.`};if(agedCount>0)return{tone:'warning' as const,title:`${agedCount} veículo(s) acima de 60 dias`,text:`${formatCurrency(agedValue)} já entrou na zona de atenção. Antecipe ações de giro antes que esse estoque passe de 90 dias.`};return{tone:'good' as const,title:'Estoque dentro da faixa saudável',text:`Idade média de ${avgStockDays.toFixed(0)} dias. Preserve margem nos carros novos e acompanhe os que se aproximam de 60 dias.`};},[stock,criticalCount,agedCount,agedValue,avgStockDays]);
  const aiInsight = selectedSellerCard ? {tone:selectedSellerCard.tone,title:`Diagnóstico de ${selectedSellerCard.name.split(' ')[0]}`,text:selectedSellerCard.diagnosis} : !closedDeals.length ? {tone:'neutral' as const,title:'Comece registrando as negociações',text:'Assim que houver vendas fechadas, o DealMaster cruza ritmo, margem, captura e estoque.'} : closedDeals.length-meter.expectedToday < -1 ? {tone:'warning' as const,title:`${Math.abs(Math.round(closedDeals.length-meter.expectedToday))} carros atrás do ritmo de hoje`,text:`Para chegar a ${performance.monthlyGoal}, a operação precisa de ${meter.dailyNeeded.toFixed(1)} carro(s) por dia trabalhado restante.`} : stats.captureRate<performance.captureGoal ? {tone:'warning' as const,title:'Volume em ritmo, captura abaixo da meta',text:`A captura está em ${stats.captureRate.toFixed(0)}%, contra meta de ${performance.captureGoal}%.`} : stats.avgMargin<performance.healthyMargin ? {tone:'warning' as const,title:'Ritmo bom, margem pede proteção',text:`A margem média está em ${stats.avgMargin.toFixed(1)}%.`} : {tone:'good' as const,title:'Operação em ritmo saudável',text:`Projeção de ${meter.projection} vendas, captura ${stats.captureRate.toFixed(0)}% e margem ${stats.avgMargin.toFixed(1)}%.`};
  const recentDeals=filtered.slice(0,4), firstName=currentUser.name?.split(' ')[0]||'Olá', todayLabel=format(new Date(),"EEEE, d 'de' MMMM",{locale:ptBR}), monthlyGoal=selectedSeller==='all'?performance.monthlyGoal:performance.sellerMonthlyGoal, monthlyProgress=Math.min((closedDeals.length/Math.max(monthlyGoal,1))*100,100), monthlyGap=Math.max(monthlyGoal-closedDeals.length,0), paceGap=closedDeals.length-(selectedSellerCard?.expected??meter.expectedToday);

  return <div className="pb-24 md:pb-12 space-y-6 md:space-y-8 animate-fade-in">
    {showPerformanceSettings&&<div className="fixed inset-0 z-[150] flex items-center justify-center bg-black/70 p-4 backdrop-blur-md"><div className="w-full max-w-2xl overflow-hidden rounded-[30px] border border-white/10 bg-zinc-950 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-zinc-500">Faturômetro</p><h3 className="mt-1 text-xl font-semibold text-white">Configuração da operação</h3></div><button onClick={()=>setShowPerformanceSettings(false)} className="grid h-10 w-10 place-items-center rounded-full bg-white/[0.06] text-zinc-400"><X size={18}/></button></div><div className="grid gap-4 p-5 md:grid-cols-2"><ConfigField label="Meta mensal" value={draftPerformance.monthlyGoal} onChange={v=>setDraftPerformance(p=>({...p,monthlyGoal:v}))}/><ConfigField label="Quinzena (% da meta)" value={draftPerformance.firstHalfPercent} onChange={v=>setDraftPerformance(p=>({...p,firstHalfPercent:v}))}/><ConfigField label="Meta de captura (%)" value={draftPerformance.captureGoal} onChange={v=>setDraftPerformance(p=>({...p,captureGoal:v}))}/><ConfigField label="Margem saudável (%)" value={draftPerformance.healthyMargin} onChange={v=>setDraftPerformance(p=>({...p,healthyMargin:v}))}/><ConfigField label="Meta vendedor / mês" value={draftPerformance.sellerMonthlyGoal} onChange={v=>setDraftPerformance(p=>({...p,sellerMonthlyGoal:v}))}/><ConfigField label="Meta vendedor / quinzena" value={draftPerformance.sellerFirstHalfGoal} onChange={v=>setDraftPerformance(p=>({...p,sellerFirstHalfGoal:v}))}/><ConfigField label="Captura vendedor (%)" value={draftPerformance.sellerCaptureGoal} onChange={v=>setDraftPerformance(p=>({...p,sellerCaptureGoal:v}))}/><div><label className="mb-2 block text-xs text-zinc-500">Feriados sem expediente</label><input value={holidayDraft} onChange={e=>setHolidayDraft(e.target.value)} className="h-12 w-full rounded-2xl border border-white/10 bg-white/[0.05] px-4 text-sm text-white outline-none"/></div></div><div className="flex justify-end gap-2 border-t border-white/10 p-5"><button onClick={()=>setShowPerformanceSettings(false)} className="rounded-2xl px-5 py-3 text-sm text-zinc-400">Cancelar</button><button onClick={savePerformance} disabled={isSavingPerformance} className="rounded-2xl bg-white px-5 py-3 text-sm font-semibold text-black">{isSavingPerformance?'Salvando…':'Salvar configuração'}</button></div></div></div>}
    <section className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="mb-1 text-sm capitalize text-zinc-500">{todayLabel}</p><h2 className="text-3xl font-semibold tracking-tight text-white md:text-4xl">Bom dia, {firstName}.</h2><p className="mt-2 text-zinc-400">Ritmo, equipe, margem e capital de estoque em uma visão.</p></div><div className="flex flex-col gap-2 sm:flex-row">{currentUser.role==='admin'&&<button onClick={()=>{setDraftPerformance(performance);setHolidayDraft(performance.holidays.join(', '));setShowPerformanceSettings(true)}} className="flex h-11 items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/[0.06] px-4 text-sm text-zinc-300"><Settings2 size={16}/> Metas</button>}<select value={selectedSeller} onChange={e=>setSelectedSeller(e.target.value)} className="h-11 rounded-2xl border border-white/10 bg-white/[0.06] px-4 text-sm text-zinc-200 outline-none"><option value="all" className="bg-zinc-900">Toda equipe</option>{availableSellers.map(s=><option key={s.id} value={s.id} className="bg-zinc-900">{s.name}</option>)}</select><select value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)} className="h-11 rounded-2xl border border-white/10 bg-white/[0.06] px-4 text-sm text-zinc-200 outline-none"><option value="all" className="bg-zinc-900">Todo período</option>{availableMonths.map(m=><option key={m} value={m} className="bg-zinc-900">{formatMonth(m)}</option>)}</select></div></section>
    <section className="relative overflow-hidden rounded-[32px] border border-white/10 bg-gradient-to-br from-zinc-800 via-zinc-900 to-black p-6 md:p-8"><div className="relative grid gap-7 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><div className="mb-5 flex items-center gap-2 text-sm text-zinc-400"><Target size={16}/> {selectedSellerCard?`Meta de ${selectedSellerCard.name}`:'Faturômetro mensal'}</div><div className="flex items-end gap-3"><span className="text-6xl font-semibold tracking-[-0.06em] text-white md:text-7xl">{closedDeals.length}</span><span className="pb-2 text-xl text-zinc-500">de {monthlyGoal}</span></div><div className="mt-6 h-2.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-white" style={{width:`${monthlyProgress}%`}}/></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><MiniMetric label="Esperado hoje" value={(selectedSellerCard?.expected??meter.expectedToday).toFixed(1)} state={paceGap>=0?'good':'warning'}/><MiniMetric label="Projeção" value={`${selectedSellerCard?.projection??meter.projection}`} state={(selectedSellerCard?.projection??meter.projection)>=monthlyGoal?'good':'warning'}/><MiniMetric label="Faltam" value={`${monthlyGap}`}/><MiniMetric label="Ritmo necessário" value={`${(selectedSellerCard?.dailyNeeded??meter.dailyNeeded).toFixed(1)}/dia`}/></div></div><button onClick={onStartNewCalculation} className="flex min-h-24 items-center justify-between rounded-[26px] bg-white px-5 py-5 text-left text-black"><div><span className="text-xs font-semibold uppercase tracking-[0.16em] text-zinc-500">Ação rápida</span><span className="block text-lg font-semibold">Nova negociação</span><span className="mt-1 block text-sm text-zinc-500">Calcule margem antes de fechar.</span></div><div className="grid h-11 w-11 place-items-center rounded-full bg-black text-white"><ArrowRight size={20}/></div></button></div></section>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><MetricCard icon={<CalendarDays size={18}/>} label="Quinzena" value={selectedSellerCard?`${selectedSellerCard.firstHalf} / ${performance.sellerFirstHalfGoal}`:`${meter.firstHalfActual} / ${meter.firstHalfGoal}`} hint={selectedSellerCard?'Meta individual':`Meta: ${performance.firstHalfPercent}% do mês`} state={(selectedSellerCard?selectedSellerCard.firstHalf>=performance.sellerFirstHalfGoal:meter.firstHalfActual>=meter.firstHalfExpected)?'good':'warning'}/><MetricCard icon={<Percent size={18}/>} label="Margem média" value={`${stats.avgMargin.toFixed(1)}%`} hint={`Saudável ≥ ${performance.healthyMargin}%`} state={stats.avgMargin>=performance.healthyMargin?'good':'warning'}/><MetricCard icon={<CarFront size={18}/>} label="Captura" value={`${stats.captureRate.toFixed(0)}%`} hint={`Meta ${selectedSellerCard?performance.sellerCaptureGoal:performance.captureGoal}%`} state={stats.captureRate>=(selectedSellerCard?performance.sellerCaptureGoal:performance.captureGoal)?'good':'warning'}/><MetricCard icon={<TrendingUp size={18}/>} label="Lucro" value={formatCurrency(stats.totalProfit)} hint={`${openDeals.length} em negociação`}/></section>
    <Insight tone={aiInsight.tone} title={aiInsight.title} text={aiInsight.text} label="Performance"/>
    <section className="rounded-[30px] border border-white/10 bg-white/[0.035] p-5 md:p-7"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Equipe</p><h3 className="mt-1 text-xl font-semibold text-white">Performance dos vendedores</h3></div><Users size={21} className="text-zinc-600"/></div><div className="grid gap-3 lg:grid-cols-2">{sellerPerformance.map((s,index)=><button key={s.id} onClick={()=>setSelectedSeller(s.id)} className="rounded-[24px] border border-white/10 bg-black/20 p-4 text-left transition hover:bg-white/[0.05]"><div className="flex items-start gap-3"><div className={`grid h-10 w-10 place-items-center rounded-full ${index===0&&s.count>0?'bg-white text-black':'bg-white/[0.06] text-zinc-400'}`}>{index===0&&s.count>0?<Trophy size={16}/>:s.name.charAt(0).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between"><p className="truncate font-medium text-white">{s.name}</p><span className={`h-2.5 w-2.5 rounded-full ${s.tone==='good'?'bg-emerald-400':s.tone==='warning'?'bg-amber-400':'bg-zinc-700'}`}/></div><p className="mt-1 text-xs text-zinc-500">{s.count}/{performance.sellerMonthlyGoal} vendas · projeção {s.projection}</p></div></div><div className="mt-4 grid grid-cols-4 gap-2"><SmallStat label="Quinzena" value={`${s.firstHalf}/${performance.sellerFirstHalfGoal}`}/><SmallStat label="Captura" value={`${s.capture.toFixed(0)}%`}/><SmallStat label="Margem" value={`${s.margin.toFixed(1)}%`}/><SmallStat label="Lucro" value={formatCurrency(s.profit)}/></div><p className="mt-3 text-xs leading-5 text-zinc-500">{s.diagnosis}</p></button>)}</div></section>
    <section className="grid gap-4 xl:grid-cols-[1.45fr_.85fr]"><div className="rounded-[30px] border border-white/10 bg-white/[0.035] p-5 md:p-7"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Faturômetro</p><h3 className="mt-1 text-xl font-semibold text-white">Real x ritmo ideal</h3></div><div className="rounded-full bg-white/[0.06] px-3 py-1.5 text-xs text-zinc-400">{formatMonth(selectedMonth)}</div></div><div className="h-[285px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{top:10,right:8,left:-22,bottom:0}}><defs><linearGradient id="dealMasterArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#fff" stopOpacity={0.22}/><stop offset="100%" stopColor="#fff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#27272a" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="label" stroke="#71717a" fontSize={10} tickLine={false} axisLine={false}/><YAxis stroke="#71717a" fontSize={10} tickLine={false} axisLine={false} allowDecimals={false}/><Tooltip contentStyle={{backgroundColor:'#18181b',border:'1px solid #3f3f46',borderRadius:16}}/><Area type="monotone" dataKey="vendas" name="Realizado" stroke="#fff" strokeWidth={2.8} fill="url(#dealMasterArea)"/><Line type="monotone" dataKey="esperado" name="Esperado" stroke="#f59e0b" strokeWidth={1.8} strokeDasharray="6 5" dot={false} connectNulls/></AreaChart></ResponsiveContainer></div></div><div className="rounded-[30px] border border-white/10 bg-white/[0.035] p-5 md:p-7"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Capital</p><h3 className="mt-1 text-xl font-semibold text-white">Saúde do estoque</h3><div className="mt-5 grid grid-cols-2 gap-3"><SmallStat label="Veículos" value={`${stock.length}`}/><SmallStat label="Idade média" value={`${avgStockDays.toFixed(0)} dias`}/><SmallStat label="Capital total" value={formatCurrency(stockValue)}/><SmallStat label="Capital +60d" value={formatCurrency(agedValue)}/></div><div className="mt-5 space-y-2">{stockBands.map(b=><button key={b.band} onClick={()=>setStockFilter(stockFilter===b.band?'all':b.band)} className={`flex w-full items-center justify-between rounded-2xl px-3.5 py-3 text-left ${stockFilter===b.band?'bg-white text-black':'bg-black/20 text-white'}`}><span className="text-sm font-medium">{b.band} dias</span><span className={`text-xs ${stockFilter===b.band?'text-zinc-600':'text-zinc-500'}`}>{b.count} · {formatCurrency(b.value)}</span></button>)}</div></div></section>
    <Insight tone={stockInsight.tone} title={stockInsight.title} text={stockInsight.text} label="DealMaster Estoque AI"/>
    <section className="rounded-[30px] border border-white/10 bg-white/[0.035] p-5 md:p-7"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Estoque</p><h3 className="mt-1 text-xl font-semibold text-white">Prioridade de giro</h3></div><div className="flex gap-2"><button onClick={()=>setStockFilter('all')} className={`rounded-full px-3 py-1.5 text-xs ${stockFilter==='all'?'bg-white text-black':'bg-white/[0.06] text-zinc-400'}`}>Todos</button><span className="rounded-full bg-red-500/10 px-3 py-1.5 text-xs text-red-400">{criticalCount} críticos</span></div></div><div className="grid gap-3 lg:grid-cols-2">{filteredStock.length===0?<EmptyState text="Nenhum veículo nesta faixa de estoque."/>:filteredStock.slice(0,12).map(item=><div key={item.id} className="rounded-[22px] border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold uppercase text-white">{item.data.licensePlate||'Sem placa'}</p><p className="mt-1 text-xs text-zinc-500">{item.userName||'Sem responsável'}</p></div><PriorityBadge priority={item.priority} days={item.days}/></div><div className="mt-4 grid grid-cols-3 gap-2"><SmallStat label="Custo" value={formatCurrency(item.cost)}/><SmallStat label="FIPE" value={formatCurrency(item.fipe)}/><SmallStat label="NF" value={formatCurrency(item.invoice)}/></div><p className="mt-3 text-xs leading-5 text-zinc-500">{item.action}</p></div>)}</div></section>
    <section className="rounded-[30px] border border-white/10 bg-white/[0.035] p-5 md:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">Atividade</p><h3 className="mt-1 text-xl font-semibold text-white">Negociações recentes</h3></div><Coins size={20} className="text-zinc-600"/></div><div className="grid gap-2 md:grid-cols-2">{recentDeals.length===0?<EmptyState text="As negociações mais recentes aparecerão aqui."/>:recentDeals.map(item=>{const closed=item.data.dealStatus==='closed';return <div key={item.id} className="flex items-center gap-3 rounded-2xl px-2 py-3"><div className={`grid h-9 w-9 place-items-center rounded-full ${closed?'bg-emerald-500/10 text-emerald-400':'bg-amber-400/10 text-amber-400'}`}>{closed?<CheckCircle2 size={16}/>:<Clock3 size={16}/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium uppercase text-white">{item.data.licensePlate||'Negociação sem placa'}</p><p className="text-xs text-zinc-500">{item.userName||'Sem vendedor'} · {closed?'Fechada':'Em andamento'}</p></div><ChevronRight size={17} className="text-zinc-700"/></div>})}</div></section>
    {commissionConfig?.enabled&&currentUser.role!=='admin'&&<section className="rounded-[30px] border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-zinc-500">Minha comissão estimada</p><p className="text-2xl font-semibold text-white">{formatCurrency(stats.totalCommission)}</p></div><CalcIcon size={20} className="text-zinc-700"/></div></section>}
  </div>;
};

const ConfigField=({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void})=><div><label className="mb-2 block text-xs text-zinc-500">{label}</label><input type="number" value={value} onChange={e=>onChange(Number(e.target.value)||0)} className="h-12 w-full rounded-2xl border border-white/10 bg-white/[0.05] px-4 text-sm text-white outline-none"/></div>;
const MiniMetric=({label,value,state='neutral'}:{label:string;value:string;state?:'neutral'|'good'|'warning'})=><div className="rounded-2xl bg-white/[0.055] p-3"><p className="text-[10px] uppercase tracking-[0.12em] text-zinc-600">{label}</p><p className={`mt-1 text-lg font-semibold ${state==='good'?'text-emerald-400':state==='warning'?'text-amber-400':'text-white'}`}>{value}</p></div>;
const MetricCard=({icon,label,value,hint,state='neutral'}:{icon:React.ReactNode;label:string;value:string;hint:string;state?:'neutral'|'good'|'warning'})=><div className="min-h-36 rounded-[26px] border border-white/10 bg-white/[0.035] p-4 md:p-5"><div className="mb-5 flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-2xl bg-white/[0.06] text-zinc-300">{icon}</span>{state!=='neutral'&&<span className={`h-2.5 w-2.5 rounded-full ${state==='good'?'bg-emerald-400':'bg-amber-400'}`}/>}</div><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 truncate text-2xl font-semibold text-white">{value}</p><p className="mt-1 truncate text-[11px] text-zinc-600">{hint}</p></div>;
const SmallStat=({label,value}:{label:string;value:string})=><div className="rounded-xl bg-white/[0.04] p-2.5"><p className="text-[9px] uppercase tracking-wide text-zinc-600">{label}</p><p className="mt-1 truncate text-sm font-semibold text-zinc-200">{value}</p></div>;
const EmptyState=({text}:{text:string})=><div className="flex min-h-32 flex-col items-center justify-center rounded-2xl border border-dashed border-white/10 p-4 text-center"><CarFront size={22} className="mb-2 text-zinc-700"/><p className="max-w-52 text-sm text-zinc-600">{text}</p></div>;
const Insight=({tone,title,text,label}:{tone:'good'|'warning'|'neutral';title:string;text:string;label:string})=><section className={`rounded-[30px] border p-6 md:p-7 ${tone==='good'?'border-emerald-500/20 bg-emerald-500/[0.07]':tone==='warning'?'border-amber-400/20 bg-amber-400/[0.07]':'border-white/10 bg-white/[0.04]'}`}><div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-white text-black"><Sparkles size={20}/></div><div className="flex-1"><span className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-400">{label}</span><h3 className="mt-1 text-xl font-semibold text-white">{title}</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-400">{text}</p></div><BrainCircuit className="hidden text-zinc-700 md:block" size={26}/></div></section>;
const PriorityBadge=({priority,days}:{priority:'healthy'|'attention'|'high'|'critical';days:number})=>{const cls=priority==='critical'?'bg-red-500/10 text-red-400':priority==='high'?'bg-amber-400/10 text-amber-400':priority==='attention'?'bg-yellow-300/10 text-yellow-300':'bg-emerald-500/10 text-emerald-400';return <span className={`flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${cls}`}>{priority!=='healthy'&&<AlertCircle size={12}/>} {days}d</span>};
export default Dashboard;