import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Building2, CarFront, CircleDollarSign, RefreshCw, Target, TrendingUp } from 'lucide-react';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { OperationalPerformanceSeller, OperationalPerformanceSnapshot, OperationalStockItem, Store, User } from '../types';
import { storeCompanyId, storeService } from '../services/storeService';
import { storeScopedOperationalService } from '../services/storeScopedOperationalService';

type PerformanceConfig = { monthlyGoal:number; captureGoal:number; healthyMargin:number };
const DEFAULTS:PerformanceConfig={monthlyGoal:70,captureGoal:60,healthyMargin:8};
type Health='green'|'yellow'|'red'|'gray';
type Row={store:Store;snapshot:OperationalPerformanceSnapshot|null;stock:OperationalStockItem[];sales:number;projection:number;margin:number;capture:number;stockCount:number;critical90:number;criticalValue:number;health:Health;score:number;mainAlert:string};
type Props={currentUser:User;companyId:string;companyName:string;embedded?:boolean};

const officialClosingRate=(item:OperationalPerformanceSeller|null|undefined)=>{if(!item)return 0;const flow=Number(item.flowTotal||0),rawRate=Number(item.closingPercent||0),rawClosing=Number(item.closing||0);if(flow>0&&rawRate>0&&rawRate<=2&&Math.abs(rawRate-rawClosing)<0.000001)return rawRate*100;return rawRate;};
const officialClosingCount=(item:OperationalPerformanceSeller|null|undefined)=>{if(!item)return 0;const flow=Number(item.flowTotal||0),rate=officialClosingRate(item);if(flow>0&&Number.isFinite(rate)){const derived=rate/100*flow,rounded=Math.round(derived);return Math.abs(derived-rounded)<0.02?rounded:Number(derived.toFixed(2));}return Number(item.closing||0);};
const totalFromSnapshot=(snapshot:OperationalPerformanceSnapshot|null):OperationalPerformanceSeller|null=>{if(!snapshot)return null;if(snapshot.total)return snapshot.total;const sellers=snapshot.sellers||[];if(!sellers.length)return null;const sum=(key:keyof OperationalPerformanceSeller)=>sellers.reduce((acc,item)=>acc+Number(item[key]||0),0);const closing=sellers.reduce((acc,item)=>acc+officialClosingCount(item),0),flow=sum('flowTotal');return {seller:'TOTAL',sellerKey:'total',passages:sum('passages'),orders:sum('orders'),flowTotal:flow,orderPercent:0,workInPeriod:sum('workInPeriod'),avgContactsPerDay:0,evaluations:sum('evaluations'),evaluationRate:0,closing,syonetSales:sum('syonetSales'),closingPercent:flow?closing/flow*100:0,marginPerCar:closing?sum('marginTotal')/closing:0,marginTotal:sum('marginTotal'),marginPercent:closing?sellers.reduce((acc,item)=>acc+Number(item.marginPercent||0)*officialClosingCount(item),0)/closing:0,captureQty:sum('captureQty'),capturePercent:closing?sum('captureQty')/closing*100:0,pipeline:sum('pipeline'),projection:sum('projection'),additionalPurchase:sum('additionalPurchase')};};

const healthFor=(input:{projection:number;margin:number;capture:number;critical90:number;stockCount:number;hasData:boolean},cfg:PerformanceConfig)=>{
 if(!input.hasData)return {health:'gray' as Health,score:0,mainAlert:'Dados operacionais indisponíveis'};
 const projectionPct=input.projection/Math.max(cfg.monthlyGoal,1)*100;
 const criticalPct=input.stockCount?input.critical90/input.stockCount*100:0;
 const tests=[projectionPct>=100?2:projectionPct>=90?1:0,input.margin>=cfg.healthyMargin?2:input.margin>=cfg.healthyMargin-1?1:0,input.capture>=cfg.captureGoal?2:input.capture>=cfg.captureGoal-10?1:0,criticalPct<=5?2:criticalPct<=10?1:0];
 const score=tests.reduce((a,b)=>a+b,0);
 const health:Health=score>=7?'green':score>=4?'yellow':'red';
 const alerts=[{gap:100-projectionPct,text:`Projeção em ${projectionPct.toFixed(0)}% da meta`},{gap:(cfg.healthyMargin-input.margin)*12,text:`Margem em ${input.margin.toFixed(1)}%`},{gap:cfg.captureGoal-input.capture,text:`Captura em ${input.capture.toFixed(1)}%`},{gap:criticalPct*1.3,text:`${input.critical90} veículo(s) com +90 dias`}].sort((a,b)=>b.gap-a.gap);
 return {health,score,mainAlert:alerts[0]?.text||'Operação dentro das faixas'};
};

const DirectorPanorama:React.FC<Props>=({currentUser,companyId,companyName,embedded=false})=>{
 const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(false);const[performance,setPerformance]=useState<PerformanceConfig>(DEFAULTS);const[lastUpdate,setLastUpdate]=useState('');
 const load=async()=>{setLoading(true);try{
  const role=String(currentUser.role||'');
  const storeList=role==='director'?await storeService.getDirectorStores(companyId):await storeService.getAll();
  const active=storeList.filter(store=>store.active&&storeCompanyId(store)===companyId);
  let cfg=DEFAULTS;
  try{const perfSnap=await getDoc(doc(db,'config/performance'));if(perfSnap.exists())cfg={...DEFAULTS,...(perfSnap.data() as Partial<PerformanceConfig>)};}catch{}
  setPerformance(cfg);
  const data=await Promise.all(active.map(async store=>{
    let snapshot:OperationalPerformanceSnapshot|null=null;
    let stock:OperationalStockItem[]=[];
    try{snapshot=await storeScopedOperationalService.getLatestPerformance(store.id,companyId);}catch{}
    try{stock=await storeScopedOperationalService.getLatestStock(store.id,companyId);}catch{}
    const total=totalFromSnapshot(snapshot),sales=officialClosingCount(total),projection=Number(total?.projection||0),margin=Number(total?.marginPercent||0),capture=Number(total?.capturePercent||0),critical=stock.filter(item=>Number(item.stockDays||0)>90);
    const result=healthFor({projection,margin,capture,critical90:critical.length,stockCount:stock.length,hasData:!!snapshot},cfg);
    return{store,snapshot,stock,sales,projection,margin,capture,stockCount:stock.length,critical90:critical.length,criticalValue:critical.reduce((s,i)=>s+Number(i.cost||0),0),...result} as Row;
  }));
  const executiveRows=data.filter(row=>!(/^teste?$/i.test(row.store.name.trim())&&!row.snapshot&&!row.stock.length));
  setRows(executiveRows);setLastUpdate(new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}));
 }catch{setRows([]);}finally{setLoading(false);}};
 useEffect(()=>{load();},[companyId]);
 useEffect(()=>{const refresh=()=>load();window.addEventListener('dealmaster:operational-data-updated',refresh);return()=>window.removeEventListener('dealmaster:operational-data-updated',refresh);},[companyId]);
 const summary=useMemo(()=>{const withData=rows.filter(r=>r.snapshot);const sales=withData.reduce((s,r)=>s+r.sales,0);const goal=withData.length*performance.monthlyGoal;const projection=withData.reduce((s,r)=>s+r.projection,0);const weightedMargin=sales?withData.reduce((s,r)=>s+r.margin*r.sales,0)/sales:0;const totalClosing=withData.reduce((s,r)=>s+officialClosingCount(totalFromSnapshot(r.snapshot)),0);const captureQty=withData.reduce((s,r)=>s+Number(totalFromSnapshot(r.snapshot)?.captureQty||0),0);const capture=totalClosing?captureQty/totalClosing*100:0;return{sales,goal,projection,weightedMargin,capture,green:rows.filter(r=>r.health==='green').length,yellow:rows.filter(r=>r.health==='yellow').length,red:rows.filter(r=>r.health==='red').length,gray:rows.filter(r=>r.health==='gray').length,stock:rows.reduce((s,r)=>s+r.stockCount,0),critical:rows.reduce((s,r)=>s+r.critical90,0)};},[rows,performance]);
 const ranking=useMemo(()=>[...rows].sort((a,b)=>{const order={green:3,yellow:2,red:1,gray:0};if(order[a.health]!==order[b.health])return order[b.health]-order[a.health];return b.projection-a.projection;}),[rows]);
 const topAlerts=useMemo(()=>[...rows].filter(r=>r.health==='red'||r.health==='yellow').sort((a,b)=>a.health===b.health?b.score-a.score:a.health==='red'?-1:1).slice(0,3),[rows]);
 const role=String(currentUser.role||'');if(role!=='admin'&&role!=='director')return null;
 return <div className={embedded?'w-full':'fixed inset-0 z-[520] overflow-y-auto bg-[#17191e] text-white'}><div className="mx-auto max-w-[1500px] p-5 md:p-8"><header className="flex flex-col gap-4 border-b border-white/10 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">Diretoria · Panorama do Grupo</p><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">{companyName}</h1><p className="mt-2 text-sm text-zinc-400">Resultado, tendência e exceções. Sem ruído operacional.</p></div><div className="flex items-center gap-3"><span className="text-xs text-zinc-500">Atualizado {lastUpdate||'agora'}</span><button onClick={load} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.04] text-zinc-300"><RefreshCw size={16} className={loading?'animate-spin':''}/></button></div></header>
 <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><ExecutiveMetric icon={<Target size={18}/>} label="Vendas / Meta" value={`${summary.sales} / ${summary.goal}`} hint={`${(summary.goal?summary.sales/summary.goal*100:0).toFixed(1)}% realizado`}/><ExecutiveMetric icon={<TrendingUp size={18}/>} label="Projeção" value={summary.projection.toFixed(1)} hint={`${(summary.goal?summary.projection/summary.goal*100:0).toFixed(1)}% da meta consolidada`}/><ExecutiveMetric icon={<CircleDollarSign size={18}/>} label="Margem MC" value={`${summary.weightedMargin.toFixed(1)}%`} hint={`Saudável ≥ ${performance.healthyMargin}%`}/><ExecutiveMetric icon={<Building2 size={18}/>} label="Captura" value={`${summary.capture.toFixed(1)}%`} hint={`Meta ${performance.captureGoal}%`}/><ExecutiveMetric icon={<CarFront size={18}/>} label="Estoque crítico" value={`${summary.critical}`} hint={`${summary.stock} veículos no grupo`}/></section>
 <section className="mt-5 grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-[28px] border border-white/10 bg-[#20242c] p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Semáforo das unidades</p><h2 className="mt-1 text-xl font-semibold">Saúde do grupo</h2></div><div className="flex gap-2 text-xs"><Pill health="green" value={summary.green}/><Pill health="yellow" value={summary.yellow}/><Pill health="red" value={summary.red}/></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{ranking.map(row=><StoreCard key={row.store.id} row={row} goal={performance.monthlyGoal}/>)}</div>{!rows.length&&!loading&&<p className="py-12 text-center text-sm text-zinc-500">Nenhuma unidade encontrada para este grupo.</p>}</div><div className="rounded-[28px] border border-white/10 bg-[#20242c] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">O que exige atenção</p><h2 className="mt-1 text-xl font-semibold">Agora</h2><div className="mt-5 space-y-3">{topAlerts.map((row,index)=><div key={row.store.id} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex items-start gap-3"><div className="mt-1"><HealthDot health={row.health}/></div><div><p className="text-xs font-bold text-zinc-500">#{index+1} · {row.store.name}</p><p className="mt-1 text-sm font-semibold text-white">{row.mainAlert}</p><p className="mt-2 text-xs text-zinc-500">Projeção {row.projection.toFixed(1)} · MC {row.margin.toFixed(1)}% · Captura {row.capture.toFixed(1)}%</p></div></div></div>)}{!topAlerts.length&&<div className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.04] p-4 text-sm text-emerald-200">Nenhuma unidade em atenção neste momento.</div>}</div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Leitura executiva</p><p className="mt-3 text-sm leading-6 text-zinc-300">{summary.red>0?`${summary.red} unidade(s) em vermelho precisam de ação imediata.`:summary.yellow>0?`${summary.yellow} unidade(s) merecem acompanhamento antes de perder ritmo.`:'O grupo está dentro das faixas executivas configuradas.'}</p></div></div></section>
 </div></div>;
};

const HealthDot=({health}:{health:Health})=><span className={`block h-3.5 w-3.5 rounded-full ${health==='green'?'bg-emerald-400 shadow-[0_0_14px_rgba(52,211,153,.55)]':health==='yellow'?'bg-amber-300 shadow-[0_0_14px_rgba(252,211,77,.45)]':health==='red'?'bg-red-400 shadow-[0_0_14px_rgba(248,113,113,.5)]':'bg-zinc-600'}`}/>;
const Pill=({health,value}:{health:Health;value:number})=><span className="flex items-center gap-1.5 rounded-full border border-white/10 bg-black/15 px-2.5 py-1"><HealthDot health={health}/>{value}</span>;
const ExecutiveMetric=({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint:string})=><div className="rounded-[24px] border border-white/10 bg-[#20242c] p-4"><div className="flex items-center gap-2 text-zinc-500">{icon}<span className="text-[11px] font-bold uppercase tracking-wide">{label}</span></div><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-zinc-500">{hint}</p></div>;
const StoreCard=({row,goal}:{row:Row;goal:number})=>{const coverage=goal?row.projection/goal*100:0;return <div className={`rounded-[22px] border p-4 ${row.health==='green'?'border-emerald-400/20 bg-emerald-400/[.035]':row.health==='yellow'?'border-amber-300/20 bg-amber-300/[.035]':row.health==='red'?'border-red-400/20 bg-red-400/[.035]':'border-white/10 bg-black/15'}`}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><HealthDot health={row.health}/><div><p className="font-semibold text-white">{row.store.name}</p><p className="mt-1 text-[11px] text-zinc-500">{row.snapshot?`${row.sales}/${goal} vendas · projeção ${row.projection.toFixed(1)}`:'Dados operacionais indisponíveis'}</p></div></div><span className="text-xs font-black text-zinc-500">{row.snapshot?`${coverage.toFixed(0)}%`:'—'}</span></div>{row.snapshot&&<><div className="mt-4 grid grid-cols-4 gap-2"><Cell label="MC" value={`${row.margin.toFixed(1)}%`}/><Cell label="Captura" value={`${row.capture.toFixed(1)}%`}/><Cell label="Estoque" value={`${row.stockCount}`}/><Cell label="+90" value={`${row.critical90}`}/></div><div className="mt-3 flex items-center gap-2 border-t border-white/10 pt-3"><AlertTriangle size={13} className={row.health==='green'?'text-emerald-300':row.health==='yellow'?'text-amber-300':'text-red-300'}/><p className="text-xs text-zinc-400">{row.health==='green'?'Dentro das faixas executivas':row.mainAlert}</p></div></>}</div>};
const Cell=({label,value}:{label:string;value:string})=><div className="rounded-xl bg-black/15 p-2"><p className="text-[9px] font-bold uppercase text-zinc-600">{label}</p><p className="mt-1 text-sm font-semibold text-zinc-200">{value}</p></div>;
export default DirectorPanorama;
