import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, Building2, CarFront, CircleDollarSign, RefreshCw, Target, TrendingUp, Trophy } from 'lucide-react';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { OperationalPerformanceSeller, OperationalPerformanceSnapshot, OperationalStockItem, Store, User } from '../types';
import { storeCompanyId, storeService } from '../services/storeService';
import { storeScopedOperationalService } from '../services/storeScopedOperationalService';
import ExecutiveOperationsPanel from './ExecutiveOperationsPanel';

type PerformanceConfig = { monthlyGoal:number; captureGoal:number; healthyMargin:number };
const DEFAULTS:PerformanceConfig={monthlyGoal:70,captureGoal:60,healthyMargin:8};
type Health='green'|'yellow'|'red'|'gray';
type Trend='up'|'flat'|'down'|'none';
type PreviousMetrics={sales:number;projection:number;margin:number;capture:number;referenceDate:string}|null;
type Row={store:Store;snapshot:OperationalPerformanceSnapshot|null;stock:OperationalStockItem[];sales:number;projection:number;margin:number;capture:number;stockCount:number;critical90:number;criticalValue:number;health:Health;score:number;mainAlert:string;trend:Trend;previousMonth:PreviousMetrics};
type Props={currentUser:User;companyId:string;companyName:string;embedded?:boolean};

const officialClosingRate=(item:OperationalPerformanceSeller|null|undefined)=>{if(!item)return 0;const flow=Number(item.flowTotal||0),rawRate=Number(item.closingPercent||0),rawClosing=Number(item.closing||0);if(flow>0&&rawRate>0&&rawRate<=2&&Math.abs(rawRate-rawClosing)<0.000001)return rawRate*100;return rawRate;};
const officialClosingCount=(item:OperationalPerformanceSeller|null|undefined)=>{if(!item)return 0;const flow=Number(item.flowTotal||0),rate=officialClosingRate(item);if(flow>0&&Number.isFinite(rate)){const derived=rate/100*flow,rounded=Math.round(derived);return Math.abs(derived-rounded)<0.02?rounded:Number(derived.toFixed(2));}return Number(item.closing||0);};
const totalFromSnapshot=(snapshot:OperationalPerformanceSnapshot|null):OperationalPerformanceSeller|null=>{if(!snapshot)return null;if(snapshot.total)return snapshot.total;const sellers=snapshot.sellers||[];if(!sellers.length)return null;const sum=(key:keyof OperationalPerformanceSeller)=>sellers.reduce((acc,item)=>acc+Number(item[key]||0),0);const closing=sellers.reduce((acc,item)=>acc+officialClosingCount(item),0),flow=sum('flowTotal');return {seller:'TOTAL',sellerKey:'total',passages:sum('passages'),orders:sum('orders'),flowTotal:flow,orderPercent:0,workInPeriod:sum('workInPeriod'),avgContactsPerDay:0,evaluations:sum('evaluations'),evaluationRate:0,closing,syonetSales:sum('syonetSales'),closingPercent:flow?closing/flow*100:0,marginPerCar:closing?sum('marginTotal')/closing:0,marginTotal:sum('marginTotal'),marginPercent:closing?sellers.reduce((acc,item)=>acc+Number(item.marginPercent||0)*officialClosingCount(item),0)/closing:0,captureQty:sum('captureQty'),capturePercent:closing?sum('captureQty')/closing*100:0,pipeline:sum('pipeline'),projection:sum('projection'),additionalPurchase:sum('additionalPurchase')};};
const metricsFromSnapshot=(snapshot:OperationalPerformanceSnapshot|null):PreviousMetrics=>{const total=totalFromSnapshot(snapshot);if(!snapshot||!total)return null;return{sales:officialClosingCount(total),projection:Number(total.projection||0),margin:Number(total.marginPercent||0),capture:Number(total.capturePercent||0),referenceDate:snapshot.referenceDate};};
const monthKey=(date:string)=>String(date||'').slice(0,7);
const previousMonthKey=(date:string)=>{const d=new Date(`${date.slice(0,10)}T12:00:00`);if(Number.isNaN(d.getTime()))return'';d.setMonth(d.getMonth()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;};
const trendFromHistory=(history:OperationalPerformanceSnapshot[],current:OperationalPerformanceSnapshot|null):Trend=>{if(!current||history.length<2)return'none';const sorted=[...history].sort((a,b)=>a.referenceDate.localeCompare(b.referenceDate));const currentIndex=sorted.findIndex(item=>item.referenceDate===current.referenceDate);const prev=currentIndex>0?sorted[currentIndex-1]:sorted[sorted.length-2];const a=metricsFromSnapshot(current),b=metricsFromSnapshot(prev);if(!a||!b)return'none';const delta=a.projection-b.projection;if(delta>=2)return'up';if(delta<=-2)return'down';return'flat';};
const previousMonthFromHistory=(history:OperationalPerformanceSnapshot[],current:OperationalPerformanceSnapshot|null):PreviousMetrics=>{if(!current)return null;const key=previousMonthKey(current.referenceDate);const candidates=history.filter(item=>monthKey(item.referenceDate)===key).sort((a,b)=>a.referenceDate.localeCompare(b.referenceDate));return metricsFromSnapshot(candidates[candidates.length-1]||null);};
const deltaLabel=(current:number,previous:number,suffix='')=>{const delta=current-previous;const sign=delta>0?'+':'';return `${sign}${delta.toFixed(1)}${suffix}`;};
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value||0);

const healthFor=(input:{projection:number;margin:number;capture:number;critical90:number;stockCount:number;hasData:boolean},cfg:PerformanceConfig)=>{
 if(!input.hasData)return {health:'gray' as Health,score:0,mainAlert:'Dados operacionais indisponíveis'};
 const projectionPct=input.projection/Math.max(cfg.monthlyGoal,1)*100;
 const criticalPct=input.stockCount?input.critical90/input.stockCount*100:0;
 const tests=[projectionPct>=100?2:projectionPct>=90?1:0,input.margin>=cfg.healthyMargin?2:input.margin>=cfg.healthyMargin-1?1:0,input.capture>=cfg.captureGoal?2:input.capture>=cfg.captureGoal-10?1:0,criticalPct<=5?2:criticalPct<=10?1:0];
 const score=tests.reduce((a,b)=>a+b,0);
 const health:Health=score>=7?'green':score>=4?'yellow':'red';
 const alerts=[{gap:100-projectionPct,text:`Projeção em ${projectionPct.toFixed(0)}% da meta`},{gap:(cfg.healthyMargin-input.margin)*12,text:`Margem em ${input.margin.toFixed(1)}%`},{gap:cfg.captureGoal-input.capture,text:`Captura em ${input.capture.toFixed(1)}%`},{gap:criticalPct*1.3,text:`${input.critical90} veículo(s) com +90 dias`}].sort((a,b)=>b.gap-a.gap);
 return {health,score,mainAlert:alerts[0]?.text||'Operação dentro das faixas'};
};

const DirectorPanorama:React.FC<Props>=({currentUser,companyId,companyName,embedded=false})=>{
 const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(false);const[performance,setPerformance]=useState<PerformanceConfig>(DEFAULTS);const[lastUpdate,setLastUpdate]=useState('');
 const load=async()=>{setLoading(true);try{
  const role=String(currentUser.role||'');
  const storeList=role==='director'?await storeService.getDirectorStores(companyId):await storeService.getAll();
  const active=storeList.filter(store=>store.active&&storeCompanyId(store)===companyId);
  let cfg=DEFAULTS;
  try{const perfSnap=await getDoc(doc(db,'config/performance'));if(perfSnap.exists())cfg={...DEFAULTS,...(perfSnap.data() as Partial<PerformanceConfig>)};}catch{}
  setPerformance(cfg);
  const data=await Promise.all(active.map(async store=>{
    let snapshot:OperationalPerformanceSnapshot|null=null;
    let stock:OperationalStockItem[]=[];
    let history:OperationalPerformanceSnapshot[]=[];
    try{snapshot=await storeScopedOperationalService.getLatestPerformance(store.id,companyId);}catch{}
    try{stock=await storeScopedOperationalService.getLatestStock(store.id,companyId);}catch{}
    try{history=await storeScopedOperationalService.getPerformanceHistory(store.id,companyId);}catch{}
    const total=totalFromSnapshot(snapshot),sales=officialClosingCount(total),projection=Number(total?.projection||0),margin=Number(total?.marginPercent||0),capture=Number(total?.capturePercent||0),critical=stock.filter(item=>Number(item.stockDays||0)>90);
    const result=healthFor({projection,margin,capture,critical90:critical.length,stockCount:stock.length,hasData:!!snapshot},cfg);
    return{store,snapshot,stock,sales,projection,margin,capture,stockCount:stock.length,critical90:critical.length,criticalValue:critical.reduce((s,i)=>s+Number(i.cost||0),0),trend:trendFromHistory(history,snapshot),previousMonth:previousMonthFromHistory(history,snapshot),...result} as Row;
  }));
  const executiveRows=data.filter(row=>!(/^teste?$/i.test(row.store.name.trim())&&!row.snapshot&&!row.stock.length));
  setRows(executiveRows);setLastUpdate(new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}));
 }catch{setRows([]);}finally{setLoading(false);}};
 useEffect(()=>{load();},[companyId]);
 useEffect(()=>{const refresh=()=>load();window.addEventListener('dealmaster:operational-data-updated',refresh);return()=>window.removeEventListener('dealmaster:operational-data-updated',refresh);},[companyId]);
 const summary=useMemo(()=>{const withData=rows.filter(r=>r.snapshot);const sales=withData.reduce((s,r)=>s+r.sales,0);const goal=withData.length*performance.monthlyGoal;const projection=withData.reduce((s,r)=>s+r.projection,0);const weightedMargin=sales?withData.reduce((s,r)=>s+r.margin*r.sales,0)/sales:0;const totalClosing=withData.reduce((s,r)=>s+officialClosingCount(totalFromSnapshot(r.snapshot)),0);const captureQty=withData.reduce((s,r)=>s+Number(totalFromSnapshot(r.snapshot)?.captureQty||0),0);const capture=totalClosing?captureQty/totalClosing*100:0;return{sales,goal,projection,weightedMargin,capture,green:rows.filter(r=>r.health==='green').length,yellow:rows.filter(r=>r.health==='yellow').length,red:rows.filter(r=>r.health==='red').length,gray:rows.filter(r=>r.health==='gray').length,stock:rows.reduce((s,r)=>s+r.stockCount,0),critical:rows.reduce((s,r)=>s+r.critical90,0)};},[rows,performance]);
 const ranking=useMemo(()=>[...rows].sort((a,b)=>{if(a.snapshot&&b.snapshot&&a.sales!==b.sales)return b.sales-a.sales;if(a.snapshot&&b.snapshot&&a.projection!==b.projection)return b.projection-a.projection;return a.store.name.localeCompare(b.store.name);}),[rows]);
 const healthRanking=useMemo(()=>[...rows].sort((a,b)=>{const order={green:3,yellow:2,red:1,gray:0};if(order[a.health]!==order[b.health])return order[b.health]-order[a.health];return b.projection-a.projection;}),[rows]);
 const topAlerts=useMemo(()=>[...rows].filter(r=>r.health==='red'||r.health==='yellow').sort((a,b)=>a.health===b.health?b.score-a.score:a.health==='red'?-1:1).slice(0,3),[rows]);
 const prevGroup=useMemo(()=>{const valid=rows.filter(r=>r.previousMonth);const sales=valid.reduce((s,r)=>s+Number(r.previousMonth?.sales||0),0);const projection=valid.reduce((s,r)=>s+Number(r.previousMonth?.projection||0),0);const weightedMargin=sales?valid.reduce((s,r)=>s+Number(r.previousMonth?.margin||0)*Number(r.previousMonth?.sales||0),0)/sales:0;const captureSales=valid.reduce((s,r)=>s+Number(r.previousMonth?.sales||0),0);const capture=captureSales?valid.reduce((s,r)=>s+Number(r.previousMonth?.capture||0)*Number(r.previousMonth?.sales||0),0)/captureSales:0;return{count:valid.length,sales,projection,margin:weightedMargin,capture};},[rows]);
 const stockAging=useMemo(()=>{
  const all=rows.flatMap(r=>r.stock);
  const range=(min:number,max:number)=>all.filter(i=>{const d=Number(i.stockDays||0);return d>=min&&d<=max;});
  const g0=range(0,30),g31=range(31,60),g61=range(61,90),g90=all.filter(i=>Number(i.stockDays||0)>90);
  const value=(list:OperationalStockItem[])=>list.reduce((s,i)=>s+Number(i.cost||0),0);
  const exposure=rows.map(r=>({name:r.store.name,count:r.stock.filter(i=>Number(i.stockDays||0)>60).length,value:r.stock.filter(i=>Number(i.stockDays||0)>60).reduce((s,i)=>s+Number(i.cost||0),0)})).filter(i=>i.count>0).sort((a,b)=>b.value-a.value);
  return{g0:{count:g0.length,value:value(g0)},g31:{count:g31.length,value:value(g31)},g61:{count:g61.length,value:value(g61)},g90:{count:g90.length,value:value(g90)},over60:g61.length+g90.length,over60Value:value(g61)+value(g90),exposure};
 },[rows]);
 const role=String(currentUser.role||'');if(role!=='admin'&&role!=='director')return null;
 return <div className={embedded?'w-full':'fixed inset-0 z-[520] overflow-y-auto bg-[#17191e] text-white'}><div className="mx-auto max-w-[1500px] p-5 md:p-8"><header className="flex flex-col gap-4 border-b border-white/10 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">Diretoria · Panorama do Grupo</p><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">{companyName}</h1><p className="mt-2 text-sm text-zinc-400">Resultado, tendência e exceções. Sem ruído operacional.</p></div><div className="flex items-center gap-3"><span className="text-xs text-zinc-500">Atualizado {lastUpdate||'agora'}</span><button onClick={load} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.04] text-zinc-300"><RefreshCw size={16} className={loading?'animate-spin':''}/></button></div></header>
 <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><ExecutiveMetric icon={<Target size={18}/>} label="Vendas / Meta" value={`${summary.sales} / ${summary.goal}`} hint={`${(summary.goal?summary.sales/summary.goal*100:0).toFixed(1)}% realizado`}/><ExecutiveMetric icon={<TrendingUp size={18}/>} label="Projeção" value={summary.projection.toFixed(1)} hint={`${(summary.goal?summary.projection/summary.goal*100:0).toFixed(1)}% da meta consolidada`}/><ExecutiveMetric icon={<CircleDollarSign size={18}/>} label="Margem MC" value={`${summary.weightedMargin.toFixed(1)}%`} hint={`Saudável ≥ ${performance.healthyMargin}%`}/><ExecutiveMetric icon={<Building2 size={18}/>} label="Captura" value={`${summary.capture.toFixed(1)}%`} hint={`Meta ${performance.captureGoal}%`}/><ExecutiveMetric icon={<CarFront size={18}/>} label="Estoque crítico" value={`${summary.critical}`} hint={`${summary.stock} veículos no grupo`}/></section>
 <section className="mt-5 grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-[28px] border border-white/10 bg-[#20242c] p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Semáforo das unidades</p><h2 className="mt-1 text-xl font-semibold">Saúde do grupo</h2></div><div className="flex gap-2 text-xs"><Pill health="green" value={summary.green}/><Pill health="yellow" value={summary.yellow}/><Pill health="red" value={summary.red}/></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{healthRanking.map(row=><StoreCard key={row.store.id} row={row} goal={performance.monthlyGoal}/>)}</div>{!rows.length&&!loading&&<p className="py-12 text-center text-sm text-zinc-500">Nenhuma unidade encontrada para este grupo.</p>}</div><div className="rounded-[28px] border border-white/10 bg-[#20242c] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">O que exige atenção</p><h2 className="mt-1 text-xl font-semibold">Agora</h2><div className="mt-5 space-y-3">{topAlerts.map((row,index)=><div key={row.store.id} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex items-start gap-3"><div className="mt-1"><HealthDot health={row.health}/></div><div><p className="text-xs font-bold text-zinc-500">#{index+1} · {row.store.name}</p><p className="mt-1 text-sm font-semibold text-white">{row.mainAlert}</p><p className="mt-2 text-xs text-zinc-500">Projeção {row.projection.toFixed(1)} · MC {row.margin.toFixed(1)}% · Captura {row.capture.toFixed(1)}%</p></div></div></div>)}{!topAlerts.length&&<div className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.04] p-4 text-sm text-emerald-200">Nenhuma unidade em atenção neste momento.</div>}</div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Leitura executiva</p><p className="mt-3 text-sm leading-6 text-zinc-300">{summary.red>0?`${summary.red} unidade(s) em vermelho precisam de ação imediata.`:summary.yellow>0?`${summary.yellow} unidade(s) merecem acompanhamento antes de perder ritmo.`:'O grupo está dentro das faixas executivas configuradas.'}</p></div></div></section>
 <section className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-[28px] border border-white/10 bg-[#20242c] p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-amber-300/10 text-amber-300"><Trophy size={18}/></div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Ranking executivo</p><h2 className="mt-1 text-xl font-semibold">Quem puxa o grupo</h2></div></div><div className="mt-5 space-y-2">{ranking.filter(r=>r.snapshot).map((row,index)=><div key={row.store.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-black/15 px-4 py-3"><div className="flex items-center gap-3"><span className="w-6 text-center text-sm font-black text-amber-300">{index+1}º</span><div><p className="text-sm font-semibold">{row.store.name}</p><p className="mt-1 text-[11px] text-zinc-500">{row.sales} vendas · projeção {row.projection.toFixed(1)} · MC {row.margin.toFixed(1)}%</p></div></div><TrendBadge trend={row.trend}/></div>)}{!ranking.some(r=>r.snapshot)&&<p className="py-8 text-center text-sm text-zinc-500">Ainda não há dados suficientes para ranking.</p>}</div></div>
 <div className="rounded-[28px] border border-white/10 bg-[#20242c] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Comparativo mensal</p><h2 className="mt-1 text-xl font-semibold">Atual x mês anterior</h2>{prevGroup.count>0?<div className="mt-5 grid grid-cols-2 gap-3"><CompareCell label="Vendas" current={String(summary.sales)} previous={String(prevGroup.sales)} delta={deltaLabel(summary.sales,prevGroup.sales)}/><CompareCell label="Projeção" current={summary.projection.toFixed(1)} previous={prevGroup.projection.toFixed(1)} delta={deltaLabel(summary.projection,prevGroup.projection)}/><CompareCell label="Margem MC" current={`${summary.weightedMargin.toFixed(1)}%`} previous={`${prevGroup.margin.toFixed(1)}%`} delta={deltaLabel(summary.weightedMargin,prevGroup.margin,' p.p.')}/><CompareCell label="Captura" current={`${summary.capture.toFixed(1)}%`} previous={`${prevGroup.capture.toFixed(1)}%`} delta={deltaLabel(summary.capture,prevGroup.capture,' p.p.')}/></div>:<div className="mt-5 rounded-2xl border border-white/10 bg-black/15 p-5 text-sm text-zinc-500">Ainda não há histórico do mês anterior suficiente para comparação.</div>}</div></section>
 <section className="mt-5 rounded-[28px] border border-white/10 bg-[#20242c] p-5"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Estoque inteligente executivo</p><h2 className="mt-1 text-xl font-semibold">Idade e capital parado</h2></div><div className="rounded-2xl border border-amber-300/15 bg-amber-300/[.04] px-4 py-3 text-right"><p className="text-[10px] font-bold uppercase tracking-wide text-amber-200/70">Acima de 60 dias</p><p className="mt-1 text-lg font-semibold text-amber-200">{stockAging.over60} veículos · {money(stockAging.over60Value)}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><StockAgeCell label="0–30 dias" count={stockAging.g0.count} value={stockAging.g0.value}/><StockAgeCell label="31–60 dias" count={stockAging.g31.count} value={stockAging.g31.value}/><StockAgeCell label="61–90 dias" count={stockAging.g61.count} value={stockAging.g61.value} attention/><StockAgeCell label="+90 dias" count={stockAging.g90.count} value={stockAging.g90.value} critical/></div><div className="mt-5 border-t border-white/10 pt-5"><p className="text-[10px] font-bold uppercase tracking-wide text-zinc-500">Maior exposição por loja</p><div className="mt-3 grid gap-2 md:grid-cols-3">{stockAging.exposure.slice(0,3).map((item,index)=><div key={item.name} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold text-zinc-500">#{index+1}</span><span className="text-xs text-zinc-500">+60 dias</span></div><p className="mt-2 text-sm font-semibold text-white">{item.name}</p><p className="mt-1 text-xl font-semibold">{item.count} veículos</p><p className="mt-1 text-xs text-zinc-500">{money(item.value)} em custo</p></div>)}{!stockAging.exposure.length&&<p className="text-sm text-zinc-500">Nenhuma unidade com estoque acima de 60 dias.</p>}</div></div></section>
 <ExecutiveOperationsPanel currentUser={currentUser} companyId={companyId} stores={rows.map(row=>row.store)}/>
 </div></div>;
};

const HealthDot=({health}:{health:Health})=><span className={`block h-3.5 w-3.5 rounded-full ${health==='green'?'bg-emerald-400 shadow-[0_0_14px_rgba(52,211,153,.55)]':health==='yellow'?'bg-amber-300 shadow-[0_0_14px_rgba(252,211,77,.45)]':health==='red'?'bg-red-400 shadow-[0_0_14px_rgba(248,113,113,.5)]':'bg-zinc-600'}`}/>;
const Pill=({health,value}:{health:Health;value:number})=><span className="flex items-center gap-1.5 rounded-full border border-white/10 bg-black/15 px-2.5 py-1"><HealthDot health={health}/>{value}</span>;
const ExecutiveMetric=({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint:string})=><div className="rounded-[24px] border border-white/10 bg-[#20242c] p-4"><div className="flex items-center gap-2 text-zinc-500">{icon}<span className="text-[11px] font-bold uppercase tracking-wide">{label}</span></div><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-zinc-500">{hint}</p></div>;
const TrendBadge=({trend}:{trend:Trend})=>{if(trend==='none')return <span className="text-[11px] text-zinc-600">sem histórico</span>;if(trend==='up')return <span className="flex items-center gap-1 text-xs font-semibold text-emerald-300"><ArrowUpRight size={15}/> melhorando</span>;if(trend==='down')return <span className="flex items-center gap-1 text-xs font-semibold text-red-300"><ArrowDownRight size={15}/> caindo</span>;return <span className="flex items-center gap-1 text-xs font-semibold text-zinc-400"><ArrowRight size={15}/> estável</span>;};
const CompareCell=({label,current,previous,delta}:{label:string;current:string;previous:string;delta:string})=><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-zinc-500">{label}</p><div className="mt-2 flex items-end justify-between gap-3"><div><p className="text-xl font-semibold text-white">{current}</p><p className="mt-1 text-[11px] text-zinc-600">Anterior {previous}</p></div><span className="text-xs font-bold text-zinc-300">{delta}</span></div></div>;
const StockAgeCell=({label,count,value,attention=false,critical=false}:{label:string;count:number;value:number;attention?:boolean;critical?:boolean})=><div className={`rounded-2xl border p-4 ${critical?'border-red-400/20 bg-red-400/[.035]':attention?'border-amber-300/20 bg-amber-300/[.035]':'border-white/10 bg-black/15'}`}><p className="text-[10px] font-bold uppercase tracking-wide text-zinc-500">{label}</p><div className="mt-2 flex items-end justify-between gap-3"><p className="text-2xl font-semibold text-white">{count}</p><span className="text-xs text-zinc-500">{money(value)}</span></div></div>;
const StoreCard=({row,goal}:{row:Row;goal:number})=>{const coverage=goal?row.projection/goal*100:0;return <div className={`rounded-[22px] border p-4 ${row.health==='green'?'border-emerald-400/20 bg-emerald-400/[.035]':row.health==='yellow'?'border-amber-300/20 bg-amber-300/[.035]':row.health==='red'?'border-red-400/20 bg-red-400/[.035]':'border-white/10 bg-black/15'}`}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><HealthDot health={row.health}/><div><p className="font-semibold text-white">{row.store.name}</p><p className="mt-1 text-[11px] text-zinc-500">{row.snapshot?`${row.sales}/${goal} vendas · projeção ${row.projection.toFixed(1)}`:'Dados operacionais indisponíveis'}</p></div></div><div className="text-right"><span className="text-xs font-black text-zinc-500">{row.snapshot?`${coverage.toFixed(0)}%`:'—'}</span>{row.snapshot&&<div className="mt-1"><TrendBadge trend={row.trend}/></div>}</div></div>{row.snapshot&&<><div className="mt-4 grid grid-cols-4 gap-2"><Cell label="MC" value={`${row.margin.toFixed(1)}%`}/><Cell label="Captura" value={`${row.capture.toFixed(1)}%`}/><Cell label="Estoque" value={`${row.stockCount}`}/><Cell label="+90" value={`${row.critical90}`}/></div><div className="mt-3 flex items-center gap-2 border-t border-white/10 pt-3"><AlertTriangle size={13} className={row.health==='green'?'text-emerald-300':row.health==='yellow'?'text-amber-300':'text-red-300'}/><p className="text-xs text-zinc-400">{row.health==='green'?'Dentro das faixas executivas':row.mainAlert}</p></div></>}</div>};
const Cell=({label,value}:{label:string;value:string})=><div className="rounded-xl bg-black/15 p-2"><p className="text-[9px] font-bold uppercase text-zinc-600">{label}</p><p className="mt-1 text-sm font-semibold text-zinc-200">{value}</p></div>;
export default DirectorPanorama;
