import React,{useEffect,useState} from 'react';
import {Landmark,Plus,X} from 'lucide-react';
import type {FinanceChartAccount,FinanceCostCenter,FinanceNature,User} from '../types';
import {financeStructureService} from '../services/financeStructureService';

type Props={open:boolean;onClose:()=>void;currentUser:User;companyId:string;storeId:string;storeName:string;onChanged?:()=>void};
const NATURE:Record<FinanceNature,string>={revenue:'Receita',expense:'Despesa',asset:'Ativo',liability:'Passivo'};

const FinanceStructurePanel:React.FC<Props>=({open,onClose,currentUser,companyId,storeId,storeName,onChanged})=>{
 const[accounts,setAccounts]=useState<FinanceChartAccount[]>([]);
 const[centers,setCenters]=useState<FinanceCostCenter[]>([]);
 const[code,setCode]=useState('');const[name,setName]=useState('');const[nature,setNature]=useState<FinanceNature>('expense');
 const[ccCode,setCcCode]=useState('');const[ccName,setCcName]=useState('');
 const[busy,setBusy]=useState('');const[error,setError]=useState('');
 const load=async()=>{try{const data=await financeStructureService.load(companyId,storeId);setAccounts(data.chartAccounts);setCenters(data.costCenters);}catch(e:any){setError(e?.message||'Falha ao carregar estrutura financeira.');}};
 useEffect(()=>{if(open)void load();},[open,companyId,storeId]);
 const addAccount=async()=>{setBusy('account');setError('');try{await financeStructureService.createChartAccount({companyId,storeId,code,name,nature,actor:currentUser});setCode('');setName('');await load();onChanged?.();}catch(e:any){setError(e?.message||'Falha ao criar conta.');}finally{setBusy('');}};
 const addCenter=async()=>{setBusy('center');setError('');try{await financeStructureService.createCostCenter({companyId,storeId,code:ccCode,name:ccName,actor:currentUser});setCcCode('');setCcName('');await load();onChanged?.();}catch(e:any){setError(e?.message||'Falha ao criar centro.');}finally{setBusy('');}};
 if(!open)return null;
 return <div className="fixed inset-0 z-[296] overflow-y-auto bg-black/80 p-3 backdrop-blur-md md:p-6" onClick={onClose}>
  <div className="mx-auto max-w-5xl overflow-hidden rounded-[30px] border border-white/10 bg-zinc-950 text-white shadow-2xl" onClick={e=>e.stopPropagation()}>
   <header className="flex items-start justify-between gap-4 border-b border-white/10 p-5 md:p-7"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-sky-300">FINANCEIRO · ESTRUTURA</p><h2 className="mt-2 text-2xl font-semibold">Plano de contas e centros de custo.</h2><p className="mt-1 text-sm text-zinc-500">{storeName}. A estrutura será usada nos lançamentos e na DRE.</p></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full bg-white/[.05] text-zinc-400"><X size={18}/></button></header>
   <div className="grid gap-5 p-5 lg:grid-cols-2 md:p-7">
    <section className="rounded-[24px] border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2"><Landmark size={16} className="text-sky-300"/><h3 className="font-semibold">Plano de contas</h3></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Código" className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs outline-none"/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da conta" className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs outline-none"/><select value={nature} onChange={e=>setNature(e.target.value as FinanceNature)} className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs"><option value="revenue">Receita</option><option value="expense">Despesa</option><option value="asset">Ativo</option><option value="liability">Passivo</option></select></div><button disabled={busy!==''} onClick={()=>void addAccount()} className="mt-2 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-sky-400 text-xs font-bold text-sky-950 disabled:opacity-50"><Plus size={14}/> ADICIONAR CONTA</button><div className="mt-4 max-h-[430px] space-y-2 overflow-y-auto">{accounts.map(item=><div key={item.chartAccountId} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-black/20 p-3"><div><p className="text-xs font-semibold">{item.code} · {item.name}</p><p className="mt-1 text-[10px] text-zinc-600">{NATURE[item.nature]}</p></div><label className="flex items-center gap-2 text-[10px] text-zinc-500"><input type="checkbox" checked={item.active} onChange={async e=>{await financeStructureService.setChartAccountActive(item,e.target.checked);await load();onChanged?.();}}/> Ativa</label></div>)}{!accounts.length&&<p className="p-6 text-center text-xs text-zinc-600">Nenhuma conta cadastrada.</p>}</div></section>
    <section className="rounded-[24px] border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2"><Landmark size={16} className="text-violet-300"/><h3 className="font-semibold">Centros de custo</h3></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><input value={ccCode} onChange={e=>setCcCode(e.target.value)} placeholder="Código" className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs outline-none"/><input value={ccName} onChange={e=>setCcName(e.target.value)} placeholder="Nome do centro" className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs outline-none"/></div><button disabled={busy!==''} onClick={()=>void addCenter()} className="mt-2 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-violet-400 text-xs font-bold text-violet-950 disabled:opacity-50"><Plus size={14}/> ADICIONAR CENTRO</button><div className="mt-4 max-h-[430px] space-y-2 overflow-y-auto">{centers.map(item=><div key={item.costCenterId} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-black/20 p-3"><div><p className="text-xs font-semibold">{item.code} · {item.name}</p></div><label className="flex items-center gap-2 text-[10px] text-zinc-500"><input type="checkbox" checked={item.active} onChange={async e=>{await financeStructureService.setCostCenterActive(item,e.target.checked);await load();onChanged?.();}}/> Ativo</label></div>)}{!centers.length&&<p className="p-6 text-center text-xs text-zinc-600">Nenhum centro cadastrado.</p>}</div></section>
   </div>
   {error&&<div className="mx-5 mb-5 rounded-xl border border-red-400/20 bg-red-400/[.05] px-3 py-2 text-xs text-red-300 md:mx-7 md:mb-7">{error}</div>}
  </div>
 </div>;
};
export default FinanceStructurePanel;
