import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ExternalLink, PencilLine, RefreshCw, Search, X } from 'lucide-react';
import { MarketPresenceItem, OperationalStockItem, User } from '../types';
import { marketPresenceService } from '../services/marketPresenceService';
import { storeScopedOperationalService } from '../services/storeScopedOperationalService';

type Props={currentUser:User;companyId:string;storeId:string;storeName:string};
type Draft={adStatus:'active'|'missing';photoStatus:'ok'|'insufficient'|'not_validated'|'missing';photoCount:string;url:string;sitePrice:string;siteKm:string;note:string;};

const clean=(value:unknown)=>String(value??'').trim();
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);
const numberOrUndefined=(value:string)=>{const raw=value.trim().replace(/R\$/gi,'').replace(/\./g,'').replace(',','.');if(!raw)return undefined;const n=Number(raw);return Number.isFinite(n)?n:undefined;};

const MarketPresenceCorrectionPanel:React.FC<Props>=({currentUser,companyId,storeId,storeName})=>{
 const[open,setOpen]=useState(false);const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[stock,setStock]=useState<OperationalStockItem[]>([]);const[audit,setAudit]=useState<MarketPresenceItem[]>([]);const[search,setSearch]=useState('');const[selectedPlate,setSelectedPlate]=useState('');const[message,setMessage]=useState('');const[draft,setDraft]=useState<Draft>({adStatus:'active',photoStatus:'not_validated',photoCount:'',url:'',sitePrice:'',siteKm:'',note:''});
 const load=async()=>{setLoading(true);try{const[s,a]=await Promise.all([storeScopedOperationalService.getLatestStock(storeId,companyId),marketPresenceService.getLatest(storeId,companyId)]);setStock(s);setAudit(a);}finally{setLoading(false);}};
 useEffect(()=>{if(open)load();},[open,companyId,storeId]);
 const byPlate=useMemo(()=>new Map(audit.map(item=>[String(item.plate||'').replace(/[^A-Z0-9]/gi,'').toUpperCase(),item])),[audit]);
 const rows=useMemo(()=>stock.filter(item=>`${item.plate} ${item.vehicle}`.toLowerCase().includes(search.trim().toLowerCase())).slice(0,60),[stock,search]);
 const selected=stock.find(item=>item.plate===selectedPlate);const selectedAudit=selected?byPlate.get(String(selected.plate||'').replace(/[^A-Z0-9]/gi,'').toUpperCase()):undefined;const latestReferenceDate=audit[0]?.referenceDate;
 const choose=(item:OperationalStockItem)=>{const current=byPlate.get(String(item.plate||'').replace(/[^A-Z0-9]/gi,'').toUpperCase());setSelectedPlate(item.plate);setDraft({adStatus:current?.adStatus||'active',photoStatus:current?.photoStatus||(current?.adStatus==='missing'?'missing':'not_validated'),photoCount:current?.photoCount!=null?String(current.photoCount):'',url:current?.url||'',sitePrice:current?.sitePrice!=null?String(current.sitePrice):'',siteKm:current?.siteKm!=null?String(current.siteKm):'',note:''});setMessage('');};
 const markActive=()=>setDraft(prev=>({...prev,adStatus:'active',photoStatus:prev.photoStatus==='missing'?'not_validated':prev.photoStatus}));
 const markMissing=()=>setDraft(prev=>({...prev,adStatus:'missing',photoStatus:'missing'}));
 const save=async()=>{if(!selected||saving)return;setSaving(true);setMessage('');try{await marketPresenceService.correct({stock:selected,audit:selectedAudit,latestReferenceDate,patch:{adStatus:draft.adStatus,photoStatus:draft.photoStatus,photoCount:numberOrUndefined(draft.photoCount),url:clean(draft.url)||undefined,sitePrice:numberOrUndefined(draft.sitePrice),siteKm:numberOrUndefined(draft.siteKm),alert:draft.adStatus==='active'?'OK':'SEM ANÚNCIO',note:draft.note},user:currentUser,storeId,companyId});setMessage(`${selected.plate}: presença digital corrigida.`);await load();window.dispatchEvent(new Event('dealmaster:operational-data-updated'));}catch(error:any){setMessage(error?.message||'Não foi possível salvar a correção.');}finally{setSaving(false);}};
 return <>
  <button onClick={()=>setOpen(true)} title="Market Presence · corrigir" className="fixed bottom-5 right-24 z-[138] hidden h-12 items-center gap-2 rounded-full border border-sky-300/20 bg-zinc-950 px-4 text-xs font-bold text-sky-200 shadow-xl"><PencilLine size={16}/> Corrigir presença</button>
  {open&&<div className="fixed inset-0 z-[590] h-[100dvh] overflow-hidden bg-black/75 backdrop-blur-md" onClick={()=>setOpen(false)}><section className="ml-auto flex h-[100dvh] w-full max-w-[620px] flex-col border-l border-white/10 bg-[#15191f] text-white shadow-2xl" onClick={e=>e.stopPropagation()}>
   <header className="flex shrink-0 items-start justify-between border-b border-white/10 p-5 sm:p-6"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-sky-300">MARKET PRESENCE · CORREÇÃO</p><h2 className="mt-2 text-2xl font-semibold">Corrigir presença digital</h2><p className="mt-1 text-sm text-zinc-500">{storeName}. Ajuste exceções sem refazer a auditoria inteira.</p></div><div className="flex gap-2"><button onClick={load} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-white/[.04] text-zinc-400"><RefreshCw size={16} className={loading?'animate-spin':''}/></button><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-white/[.04] text-zinc-400"><X size={18}/></button></div></header>
   <div className="min-h-0 flex-1 overflow-y-auto p-5 sm:p-6">
    <div className="flex h-11 items-center gap-2 rounded-2xl border border-white/10 bg-black/20 px-3"><Search size={15} className="text-zinc-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Digite placa ou modelo" className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-zinc-700"/></div>
    {!selected&&<div className="mt-4 space-y-2">{rows.map(item=>{const current=byPlate.get(String(item.plate||'').replace(/[^A-Z0-9]/gi,'').toUpperCase());return <button key={item.id} onClick={()=>choose(item)} className="w-full rounded-2xl border border-white/10 bg-white/[.025] p-4 text-left transition hover:border-sky-300/25"><div className="flex items-center justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-bold text-white">{item.plate}</span><span className="text-sm text-zinc-400">{item.vehicle}</span></div><p className="mt-1 text-xs text-zinc-600">Custo {money(Number(item.cost)||0)} · Venda {money(Number(item.askingPrice)||0)}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold ${current?.adStatus==='active'?'bg-emerald-400/10 text-emerald-300':'bg-red-400/10 text-red-300'}`}>{current?.adStatus==='active'?'ANUNCIADO':'SEM ANÚNCIO'}</span></div></button>;})}{!rows.length&&<div className="rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-zinc-600">Nenhum veículo encontrado.</div>}</div>}
    {selected&&<div className="mt-4 space-y-4"><button onClick={()=>{setSelectedPlate('');setMessage('');}} className="text-xs font-bold text-sky-300">← ESCOLHER OUTRO VEÍCULO</button><div className="rounded-[24px] border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-lg font-bold">{selected.plate}</span><span className="text-zinc-400">{selected.vehicle}</span></div><p className="mt-2 text-xs text-zinc-600">Última auditoria: {selectedAudit?.referenceDate||latestReferenceDate||'sem data'}{selectedAudit?.url?' · possui URL salva':''}</p></div>
     <div className="grid grid-cols-2 gap-2"><button onClick={markActive} className={`rounded-2xl border px-4 py-3 text-sm font-bold ${draft.adStatus==='active'?'border-emerald-300/30 bg-emerald-400/10 text-emerald-200':'border-white/10 bg-white/[.03] text-zinc-400'}`}>✓ ANUNCIADO</button><button onClick={markMissing} className={`rounded-2xl border px-4 py-3 text-sm font-bold ${draft.adStatus==='missing'?'border-red-300/30 bg-red-400/10 text-red-200':'border-white/10 bg-white/[.03] text-zinc-400'}`}>SEM ANÚNCIO</button></div>
     {draft.adStatus==='active'&&<div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-zinc-500">Fotos<select value={draft.photoStatus} onChange={e=>setDraft(prev=>({...prev,photoStatus:e.target.value as Draft['photoStatus']}))} className="mt-1.5 h-11 w-full rounded-xl border border-white/10 bg-zinc-900 px-3 text-sm text-white"><option value="not_validated">Não validadas</option><option value="ok">Fotos OK</option><option value="insufficient">Mídia insuficiente</option></select></label><label className="text-xs text-zinc-500">Quantidade de fotos<input value={draft.photoCount} onChange={e=>setDraft(prev=>({...prev,photoCount:e.target.value}))} inputMode="numeric" className="mt-1.5 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm text-white outline-none"/></label></div>}
     <label className="block text-xs text-zinc-500">URL do anúncio<input value={draft.url} onChange={e=>setDraft(prev=>({...prev,url:e.target.value}))} placeholder="https://..." className="mt-1.5 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm text-white outline-none"/></label>
     <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-zinc-500">Preço no site<input value={draft.sitePrice} onChange={e=>setDraft(prev=>({...prev,sitePrice:e.target.value}))} inputMode="decimal" className="mt-1.5 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm text-white outline-none"/></label><label className="text-xs text-zinc-500">KM no site<input value={draft.siteKm} onChange={e=>setDraft(prev=>({...prev,siteKm:e.target.value}))} inputMode="numeric" className="mt-1.5 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm text-white outline-none"/></label></div>
     <label className="block text-xs text-zinc-500">Observação da correção<textarea value={draft.note} onChange={e=>setDraft(prev=>({...prev,note:e.target.value}))} placeholder="Ex.: anúncio conferido manualmente no site" rows={3} className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white outline-none"/></label>
     <button onClick={save} disabled={saving} className="flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-sky-300 text-sm font-black text-sky-950 disabled:opacity-50"><CheckCircle2 size={17}/>{saving?'SALVANDO...':'SALVAR CORREÇÃO'}</button>
     {draft.url&&<a href={draft.url} target="_blank" rel="noreferrer" className="flex h-11 items-center justify-center gap-2 rounded-2xl border border-white/10 text-xs font-bold text-zinc-300">Abrir anúncio <ExternalLink size={14}/></a>}
     {message&&<div className="rounded-2xl border border-sky-300/15 bg-sky-300/[.05] px-4 py-3 text-sm text-sky-100">{message}</div>}
    </div>}
   </div>
  </section></div>}
 </>;
};

export default MarketPresenceCorrectionPanel;
