import React, { useEffect, useMemo, useState } from 'react';
import { ExternalLink, FileText, Megaphone, RefreshCw, Search, X } from 'lucide-react';
import { MarketPresenceItem, OperationalStockItem } from '../types';
import { marketPresenceService } from '../services/marketPresenceService';
import { storeScopedOperationalService } from '../services/storeScopedOperationalService';

type Props={companyId:string;storeId:string;storeName:string};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);
const clean=(v:unknown)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]||m));

const MarketPresencePanel:React.FC<Props>=({companyId,storeId,storeName})=>{
 const[open,setOpen]=useState(false);
 const[loading,setLoading]=useState(false);
 const[stock,setStock]=useState<OperationalStockItem[]>([]);
 const[audit,setAudit]=useState<MarketPresenceItem[]>([]);
 const[search,setSearch]=useState('');
 const load=async()=>{setLoading(true);try{const[s,a]=await Promise.all([storeScopedOperationalService.getLatestStock(storeId,companyId),marketPresenceService.getLatest(storeId,companyId)]);setStock(s);setAudit(a);}finally{setLoading(false);}};
 useEffect(()=>{if(open)load();const refresh=()=>{if(open)load();};window.addEventListener('dealmaster:operational-data-updated',refresh);return()=>window.removeEventListener('dealmaster:operational-data-updated',refresh);},[open,companyId,storeId]);
 const summary=useMemo(()=>marketPresenceService.summarize(stock,audit),[stock,audit]);
 const audited=summary.rows.length-summary.unverified.length;
 const ready=summary.rows.filter(r=>r.audit?.adStatus==='active'&&r.audit.photoStatus==='ok').length;
 const unverifiedCapital=summary.unverified.reduce((sum,r)=>sum+(Number(r.stock.cost)||0),0);
 const rows=useMemo(()=>summary.rows.filter(({stock:item,audit:a})=>{const q=search.trim().toLowerCase();return !q||`${item.plate} ${item.vehicle} ${a?.alert||''}`.toLowerCase().includes(q);}).sort((a,b)=>priorityScore(b)-priorityScore(a)),[summary.rows,search]);
 const report=()=>{const status=(a?:MarketPresenceItem)=>!a?'AGUARDANDO AUDITORIA':a.adStatus==='missing'?'SEM ANÚNCIO':a.photoStatus==='insufficient'?'MÍDIA CRÍTICA':a.photoStatus==='not_validated'?'VALIDAR FOTOS':'PRONTO';const table=rows.map(({stock:s,audit:a})=>`<tr><td><b>${clean(s.plate)}</b><br>${clean(s.vehicle)}</td><td>${clean(s.stockDays)} dias</td><td>${clean(money(Number(s.cost)||0))}</td><td><b>${status(a)}</b></td><td>${a?.photoCount??'-'}</td><td>${a?.url?'URL registrada':'-'}</td></tr>`).join('');const w=window.open('','_blank','width=1100,height=800');if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Motyq Market Presence</title><style>body{font-family:Arial;color:#111;padding:24px}h1{margin:0}p{color:#666}table{width:100%;border-collapse:collapse;margin-top:20px;font-size:12px}th{background:#111;color:#fff;text-align:left;padding:9px}td{border-bottom:1px solid #ddd;padding:9px;vertical-align:top}.cards{display:flex;gap:10px;margin:18px 0}.card{border:1px solid #ddd;padding:12px;border-radius:8px;min-width:140px}.v{font-size:22px;font-weight:bold}</style></head><body><h1>Market Presence</h1><p>${clean(storeName)} · estoque atual x auditoria compatível</p><div class="cards"><div class="card">Estoque<div class="v">${stock.length}</div></div><div class="card">Auditados<div class="v">${audited}</div></div><div class="card">Aguardando<div class="v">${summary.unverified.length}</div></div><div class="card">Sem anúncio<div class="v">${summary.missingAd.length}</div></div></div><table><thead><tr><th>Veículo</th><th>Estoque</th><th>Custo</th><th>Status</th><th>Fotos</th><th>Anúncio</th></tr></thead><tbody>${table}</tbody></table><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close();};
 const priorityTitle=summary.unverified.length?`${summary.unverified.length} carro(s) aguardam nova auditoria`:summary.missingAd.length?`${summary.missingAd.length} carro(s) precisam entrar no ar`:'Presença digital em dia';
 const priorityText=summary.unverified.length?'O estoque foi substituído depois da última auditoria. Importe uma nova Auditoria Site para classificar anúncio, fotos, preço e KM com segurança.':summary.insufficient.length?`${summary.insufficient.length} anúncio(s) também têm mídia insuficiente.`:'Nenhuma pendência crítica validada no momento.';
 return <>
  <button onClick={()=>setOpen(true)} title="Market Presence" className="fixed bottom-36 right-3 z-[139] grid h-12 w-12 place-items-center rounded-full border border-sky-400/20 bg-zinc-950/95 text-sky-300 shadow-2xl md:right-5"><Megaphone size={18}/></button>
  {open&&<div className="fixed inset-0 z-[260] overflow-y-auto bg-black/80 p-3 backdrop-blur-md md:p-6" onClick={()=>setOpen(false)}><div className="mx-auto max-w-6xl overflow-hidden rounded-[32px] border border-white/10 bg-zinc-950 shadow-2xl" onClick={e=>e.stopPropagation()}>
   <header className="flex items-start justify-between border-b border-white/10 p-5 md:p-7"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-sky-300"><Megaphone size={15}/> Stock Intelligence · Market Presence</div><h3 className="text-2xl font-semibold text-white">A vitrine digital do estoque</h3><p className="mt-2 text-sm text-zinc-500">{storeName}. Cruza apenas o estoque atual com a auditoria feita para esse mesmo lote.</p></div><div className="flex gap-2"><button onClick={report} title="Relatório gerencial" className="flex h-10 items-center gap-2 rounded-full border border-white/10 bg-white/[.05] px-3 text-xs font-semibold text-zinc-300"><FileText size={15}/><span className="hidden sm:inline">Relatório</span></button><button onClick={load} className="grid h-10 w-10 place-items-center rounded-full bg-white/[.05] text-zinc-400"><RefreshCw size={16} className={loading?'animate-spin':''}/></button><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-white/[.05] text-zinc-400"><X size={18}/></button></div></header>
   <div className="p-5 md:p-7">
    {summary.unverified.length>0&&<div className="mb-5 rounded-[22px] border border-sky-300/20 bg-sky-300/[.06] p-4"><p className="text-sm font-semibold text-sky-100">Nova fotografia de estoque detectada</p><p className="mt-1 text-sm leading-6 text-sky-100/65">A auditoria anterior não está sendo usada para classificar este estoque. Importe uma nova Auditoria Site para atualizar a presença digital.</p></div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Estoque físico" value={`${stock.length}`} note="lote atual"/><Metric label="Auditados" value={`${audited}`} note="neste lote"/><Metric label="Prontos para vender" value={`${ready}`} note="anúncio + fotos OK" good/><Metric label="Sem anúncio" value={`${summary.missingAd.length}`} note={money(summary.darkCapital)} danger={summary.missingAd.length>0}/><Metric label="Mídia insuficiente" value={`${summary.insufficient.length}`} note="fotos críticas" warn={summary.insufficient.length>0}/><Metric label="Aguardando auditoria" value={`${summary.unverified.length}`} note={money(unverifiedCapital)} info={summary.unverified.length>0}/></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_.7fr]"><div className="rounded-[26px] border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-semibold uppercase tracking-[.13em] text-zinc-600">Capital x exposição validada</p><div className="mt-4 grid grid-cols-3 gap-3"><Capital label="Exposto" value={summary.exposedCapital} good/><Capital label="Sem exposição" value={summary.darkCapital} danger/><Capital label="Não auditado" value={unverifiedCapital}/></div><p className="mt-4 text-sm leading-6 text-zinc-500">Capital só entra como “sem exposição” quando uma auditoria compatível confirma que o anúncio está ausente. Veículo ainda não auditado não é tratado como erro.</p></div><div className="rounded-[26px] border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-semibold uppercase tracking-[.13em] text-zinc-600">Prioridade comercial</p><p className="mt-2 text-lg font-semibold text-white">{priorityTitle}</p><p className="mt-2 text-sm leading-6 text-zinc-500">{priorityText}</p></div></div>
    <div className="mt-5 rounded-[26px] border border-white/10 bg-white/[.025] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.13em] text-zinc-600">Veículo por veículo</p><h4 className="mt-1 text-lg font-semibold text-white">Presença digital do estoque</h4></div><div className="flex h-10 items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-3"><Search size={14} className="text-zinc-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Placa ou modelo" className="bg-transparent text-sm text-white outline-none placeholder:text-zinc-700"/></div></div><div className="mt-4 max-h-[430px] space-y-2 overflow-y-auto pr-1">{rows.map(({stock:item,audit:a})=><div key={item.id} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-semibold text-white">{item.plate}</span><span className="text-sm text-zinc-400">{item.vehicle}</span><Status audit={a}/>{Number(item.stockDays)>=61&&<span className="rounded-full bg-red-400/10 px-2 py-1 text-[10px] font-semibold text-red-300">{item.stockDays} DIAS</span>}</div><p className="mt-1 text-xs text-zinc-600">Custo {money(Number(item.cost)||0)} · Venda {money(Number(item.askingPrice)||0)}{a?.photoCount!=null?` · ${a.photoCount} fotos`:''}</p>{a?.alert&&a.alert!=='OK'&&<p className="mt-1.5 text-xs text-amber-300/80">{a.alert}</p>}</div>{a?.url&&<a href={a.url} target="_blank" rel="noreferrer" className="flex shrink-0 items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs font-semibold text-zinc-300">Abrir anúncio <ExternalLink size={13}/></a>}</div>)}</div></div>
   </div>
  </div></div>}
 </>;
};
const priorityScore=(r:{stock:OperationalStockItem;audit?:MarketPresenceItem})=>(!r.audit?5:r.audit.adStatus==='missing'?4:r.audit.photoStatus==='insufficient'?3:r.audit.photoStatus==='not_validated'?2:0)+(Number(r.stock.stockDays)>=61?2:0);
const Status=({audit}:{audit?:MarketPresenceItem})=>{if(!audit)return <span className="rounded-full bg-sky-300/10 px-2 py-1 text-[10px] font-semibold text-sky-200">AGUARDANDO AUDITORIA</span>;if(audit.adStatus==='missing')return <span className="rounded-full bg-red-400/10 px-2 py-1 text-[10px] font-semibold text-red-300">SEM ANÚNCIO</span>;if(audit.photoStatus==='insufficient')return <span className="rounded-full bg-amber-400/10 px-2 py-1 text-[10px] font-semibold text-amber-300">MÍDIA CRÍTICA</span>;if(audit.photoStatus==='not_validated')return <span className="rounded-full bg-amber-400/10 px-2 py-1 text-[10px] font-semibold text-amber-300">VALIDAR FOTOS</span>;return <span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-semibold text-emerald-300">PRONTO</span>;};
const Metric=({label,value,note,good,warn,danger,info}:{label:string;value:string;note:string;good?:boolean;warn?:boolean;danger?:boolean;info?:boolean})=><div className={`rounded-[22px] border p-4 ${danger?'border-red-400/20 bg-red-400/[.05]':warn?'border-amber-400/20 bg-amber-400/[.05]':good?'border-emerald-400/20 bg-emerald-400/[.05]':info?'border-sky-300/20 bg-sky-300/[.05]':'border-white/10 bg-white/[.03]'}`}><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-[11px] text-zinc-600">{note}</p></div>;
const Capital=({label,value,good,danger}:{label:string;value:number;good?:boolean;danger?:boolean})=><div className={`rounded-2xl border p-4 ${danger?'border-red-400/15 bg-red-400/[.04]':good?'border-emerald-400/15 bg-emerald-400/[.04]':'border-white/10'}`}><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-xl font-semibold text-white">{money(value)}</p></div>;
export default MarketPresencePanel;
