import React, { useMemo, useState } from 'react';
import { CheckCircle2, Crown, LockKeyhole, X } from 'lucide-react';
import { Company } from '../types';
import { MODULES, moduleEnabled, PLAN_META } from '../services/planEntitlementService';

const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value);

const PlanAccessBadge:React.FC<{company:Company}>=({company})=>{
 const[open,setOpen]=useState(false);
 const enabled=useMemo(()=>MODULES.filter(module=>moduleEnabled(company,module.id)),[company]);
 const locked=useMemo(()=>MODULES.filter(module=>!moduleEnabled(company,module.id)),[company]);
 const meta=PLAN_META[company.plan];
 if(company.status==='suspended')return <button onClick={()=>setOpen(true)} className="fixed right-4 top-3 z-[138] rounded-full border border-red-400/20 bg-red-500/10 px-3 py-1.5 text-[11px] font-semibold text-red-300">Plano suspenso</button>;
 return <><button onClick={()=>setOpen(true)} title="Plano e módulos" className="fixed right-4 top-3 z-[138] flex items-center gap-1.5 rounded-full border border-white/10 bg-zinc-950/90 px-3 py-1.5 text-[11px] font-semibold text-zinc-300 shadow-lg backdrop-blur-xl hover:bg-zinc-900"><Crown size={12} className="text-violet-300"/>{meta.label}<span className="text-zinc-600">· {enabled.length}/{MODULES.length}</span></button>
 {open&&<div className="fixed inset-0 z-[300] overflow-y-auto bg-black/75 p-3 backdrop-blur-md md:p-6" onClick={()=>setOpen(false)}><div className="mx-auto max-w-3xl overflow-hidden rounded-[30px] border border-white/10 bg-zinc-950 shadow-2xl" onClick={event=>event.stopPropagation()}><header className="flex items-start justify-between border-b border-white/10 p-5 md:p-6"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.15em] text-violet-300"><Crown size={14}/> Seu Motyq</div><h3 className="text-2xl font-semibold text-white">Plano {meta.label}</h3><p className="mt-1 text-sm text-zinc-500">{company.name} · {money(meta.price)}/mês</p></div><button onClick={()=>setOpen(false)} className="grid h-9 w-9 place-items-center rounded-full bg-white/[0.05] text-zinc-400"><X size={17}/></button></header><div className="p-5 md:p-6"><div className="grid gap-3 sm:grid-cols-3"><Info label="Módulos ativos" value={`${enabled.length}`}/><Info label="Não incluídos" value={`${locked.length}`}/><Info label="Status" value={company.status==='trial'?'Avaliação':'Ativo'}/></div><div className="mt-5 grid gap-3 md:grid-cols-2">{enabled.map(module=><div key={module.id} className="flex gap-3 rounded-2xl border border-emerald-400/10 bg-emerald-400/[0.035] p-4"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-emerald-300"/><div><p className="text-sm font-semibold text-white">{module.label}</p><p className="mt-1 text-xs leading-5 text-zinc-500">{module.description}</p></div></div>)}{locked.map(module=><div key={module.id} className="flex gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 opacity-75"><LockKeyhole size={17} className="mt-0.5 shrink-0 text-zinc-600"/><div><p className="text-sm font-semibold text-zinc-300">{module.label}</p><p className="mt-1 text-xs leading-5 text-zinc-600">Disponível no plano {PLAN_META[module.minimumPlan].label} ou como módulo adicional.</p></div></div>)}</div>{locked.length>0&&<div className="mt-5 rounded-2xl border border-violet-400/15 bg-violet-400/[0.045] p-4 text-sm leading-6 text-violet-200/70">Os módulos bloqueados não desaparecem do produto comercial: ficam identificados como possibilidades de upgrade. O administrador da plataforma pode liberar um módulo adicional sem mudar o plano inteiro.</div>}</div></div></div>}
 </>;
};
const Info=({label,value}:{label:string;value:string})=><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="text-xs text-zinc-600">{label}</p><p className="mt-1 text-xl font-semibold text-white">{value}</p></div>;
export default PlanAccessBadge;