import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, CircleDollarSign, Clock3, Plus, RefreshCw, Search, Trash2, Wrench, X } from 'lucide-react';
import { OperationalStockItem, PrepOrder, PrepOrderStatus, PrepServiceStatus, User } from '../types';
import { prepTrackService } from '../services/prepTrackService';
import { storeScopedOperationalService } from '../services/storeScopedOperationalService';

type Props={currentUser:User;companyId:string;storeId:string;storeName:string};
const SERVICE_TYPES=['Troca de óleo','Mecânica','Higienização','Auto elétrica','Funilaria / pintura','Pneus','Estética','Vidros','Acessórios','Outros'];
const ORDER_LABELS:Record<PrepOrderStatus,string>={triage:'Triagem',preparing:'Em preparação',waiting_approval:'Aguardando aprovação',waiting_part:'Aguardando peça',ready:'Pronto',showroom:'Showroom',delivery:'Entrega',delivered:'Entregue'};
const SERVICE_LABELS:Record<PrepServiceStatus,string>={pending:'Pendente',approved:'Aprovado',in_service:'No prestador',waiting_part:'Aguardando peça',done:'Concluído',cancelled:'Cancelado'};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);
const dateValue=(v?:string)=>v?String(v).slice(0,10):'';

const PrepTrackPanel:React.FC<Props>=({currentUser,companyId,storeId,storeName})=>{
 const[open,setOpen]=useState(false);const[loading,setLoading]=useState(false);const[stock,setStock]=useState<OperationalStockItem[]>([]);const[orders,setOrders]=useState<PrepOrder[]>([]);const[selectedId,setSelectedId]=useState('');const[search,setSearch]=useState('');
 const[serviceType,setServiceType]=useState(SERVICE_TYPES[0]);const[provider,setProvider]=useState('');const[estimatedCost,setEstimatedCost]=useState('');const[dueAt,setDueAt]=useState('');const[notes,setNotes]=useState('');
 const load=async()=>{setLoading(true);try{const[s,o]=await Promise.all([storeScopedOperationalService.getLatestStock(storeId,companyId),prepTrackService.getOrders(companyId,storeId)]);setStock(s);setOrders(o);if(selectedId&&!o.some(item=>item.id===selectedId))setSelectedId('');}finally{setLoading(false);}};
 useEffect(()=>{if(open)load();},[open,companyId,storeId]);
 const selected=orders.find(item=>item.id===selectedId)||null;
 const stockByPlate=useMemo(()=>new Map(stock.map(item=>[String(item.plate).toUpperCase().replace(/[^A-Z0-9]/g,''),item])),[stock]);
 const visible=useMemo(()=>orders.filter(item=>`${item.plate} ${item.vehicle}`.toLowerCase().includes(search.trim().toLowerCase())),[orders,search]);
 const active=orders.filter(o=>!['showroom','delivery','delivered'].includes(o.status));const overdue=orders.filter(o=>o.services.some(s=>s.status!=='done'&&s.status!=='cancelled'&&s.dueAt&&new Date(`${s.dueAt}T23:59:59`).getTime()<Date.now()));const soldPriority=active.filter(o=>o.sold);const openCost=active.reduce((sum,o)=>sum+o.services.filter(s=>s.status!=='cancelled').reduce((a,s)=>a+(Number(s.finalCost)||Number(s.estimatedCost)||0),0),0);
 const save=async(next:PrepOrder)=>{await prepTrackService.saveOrder(next);setOrders(prev=>prev.map(item=>item.id===next.id?{...next,updatedAt:new Date().toISOString()}:item));};
 const createFromStock=async(item:OperationalStockItem)=>{const existing=orders.find(o=>o.plate===item.plate);if(existing){setSelectedId(existing.id);return;}const created=await prepTrackService.createOrder({plate:item.plate,vehicle:item.vehicle,companyId,storeId,createdBy:currentUser.email});setOrders(prev=>[created,...prev]);setSelectedId(created.id);};
 const addService=async()=>{if(!selected)return;const next=await prepTrackService.addService(selected,{type:serviceType,provider:provider.trim(),status:'pending',estimatedCost:Number(String(estimatedCost).replace(',','.'))||0,finalCost:0,dueAt:dueAt||undefined,notes:notes.trim()||undefined});setOrders(prev=>prev.map(item=>item.id===next.id?next:item));setProvider('');setEstimatedCost('');setDueAt('');setNotes('');};
 const updateService=async(id:string,patch:any)=>{if(!selected)return;await save({...selected,services:selected.services.map(s=>s.id===id?{...s,...patch}:s)});};
 const removeService=async(id:string)=>{if(!selected)return;const next=await prepTrackService.removeService(selected,id);setOrders(prev=>prev.map(item=>item.id===next.id?next:item));};
 const candidates=stock.filter(item=>!orders.some(o=>o.plate===item.plate)).slice(0,12);
 return <><button onClick={()=>setOpen(true)} title="PrepTrack · preparação" className="fixed right-5 z-[139] grid h-12 w-12 place-items-center rounded-full border border-amber-400/25 bg-zinc-950/95 text-amber-300 shadow-2xl" style={{bottom:380}}><Wrench size={18}/></button>
 {open&&<div className="fixed inset-0 z-[270] overflow-y-auto bg-black/80 p-3 backdrop-blur-md md:p-6" onClick={()=>setOpen(false)}><div className="mx-auto max-w-7xl overflow-hidden rounded-[32px] border border-white/10 bg-zinc-950 shadow-2xl" onClick={e=>e.stopPropagation()}><header className="flex flex-col gap-4 border-b border-white/10 p-5 md:flex-row md:items-center md:justify-between md:p-7"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-amber-300"><Wrench size={15}/> PrepTrack · preparação</div><h3 className="mt-2 text-2xl font-semibold text-white">Do pátio ao showroom, sem carro perdido no caminho.</h3><p className="mt-2 text-sm text-zinc-500">{storeName}. Serviços, prestadores, custos, prazos e destino final por placa.</p></div><div className="flex gap-2"><button onClick={load} className="grid h-10 w-10 place-items-center rounded-full bg-white/[.05] text-zinc-400"><RefreshCw size={16} className={loading?'animate-spin':''}/></button><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-white/[.05] text-zinc-400"><X size={18}/></button></div></header>
 <div className="p-5 md:p-7"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Wrench size={16}/>} label="Em preparação" value={`${active.length}`} note={`${orders.length} ordens no total`}/><Metric icon={<AlertTriangle size={16}/>} label="Atrasados" value={`${overdue.length}`} note="previsão vencida" danger={overdue.length>0}/><Metric icon={<CheckCircle2 size={16}/>} label="Vendidos prioritários" value={`${soldPriority.length}`} note="acelerar entrega" warn={soldPriority.length>0}/><Metric icon={<CircleDollarSign size={16}/>} label="Custo em aberto" value={money(openCost)} note="estimado + realizado"/></section>
 <section className="mt-5 grid gap-4 xl:grid-cols-[.78fr_1.22fr]"><div className="rounded-[26px] border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-3"><Search size={14} className="text-zinc-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Placa ou modelo" className="h-10 w-full bg-transparent text-sm text-white outline-none placeholder:text-zinc-700"/></div><div className="mt-3 max-h-[560px] space-y-2 overflow-y-auto pr-1">{visible.map(order=>{const isLate=order.services.some(s=>s.status!=='done'&&s.status!=='cancelled'&&s.dueAt&&new Date(`${s.dueAt}T23:59:59`).getTime()<Date.now());return <button key={order.id} onClick={()=>setSelectedId(order.id)} className={`w-full rounded-2xl border p-4 text-left ${selectedId===order.id?'border-amber-400/30 bg-amber-400/[.07]':'border-white/10 bg-black/20'}`}><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-semibold text-white">{order.plate}</span>{order.sold&&<span className="rounded-full bg-red-400/10 px-2 py-1 text-[10px] font-bold text-red-300">VENDIDO</span>}{isLate&&<span className="rounded-full bg-amber-400/10 px-2 py-1 text-[10px] font-bold text-amber-300">ATRASADO</span>}</div><p className="mt-1 text-sm text-zinc-400">{order.vehicle}</p></div><span className="text-[10px] font-semibold uppercase text-zinc-500">{ORDER_LABELS[order.status]}</span></div><p className="mt-3 text-xs text-zinc-600">{order.services.filter(s=>s.status==='done').length}/{order.services.length} serviços concluídos · {money(order.services.reduce((a,s)=>a+(Number(s.finalCost)||Number(s.estimatedCost)||0),0))}</p></button>})}{!visible.length&&<div className="rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-zinc-600">Nenhuma ordem de preparação ainda.</div>}</div></div>
 <div className="rounded-[26px] border border-white/10 bg-white/[.025] p-5">{selected?<OrderDetail order={selected} stock={stockByPlate.get(selected.plate)} onSave={save} onAddService={addService} onServiceChange={updateService} onRemoveService={removeService} serviceType={serviceType} setServiceType={setServiceType} provider={provider} setProvider={setProvider} estimatedCost={estimatedCost} setEstimatedCost={setEstimatedCost} dueAt={dueAt} setDueAt={setDueAt} notes={notes} setNotes={setNotes}/>:<><p className="text-xs font-semibold uppercase tracking-[.14em] text-zinc-600">Nova preparação</p><h4 className="mt-1 text-lg font-semibold text-white">Selecione um carro do estoque</h4><p className="mt-2 text-sm text-zinc-500">A ordem nasce vinculada à placa. Depois você adiciona somente os serviços necessários.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{candidates.map(item=><button key={item.id} onClick={()=>createFromStock(item)} className="rounded-2xl border border-white/10 bg-black/20 p-4 text-left hover:border-amber-400/30"><div className="flex items-center justify-between"><span className="font-mono text-sm font-semibold text-white">{item.plate}</span><Plus size={15} className="text-amber-300"/></div><p className="mt-1 truncate text-sm text-zinc-400">{item.vehicle}</p><p className="mt-2 text-xs text-zinc-600">{item.stockDays} dias em estoque</p></button>)}</div>{!candidates.length&&<div className="mt-4 rounded-2xl border border-dashed border-white/10 p-6 text-sm text-zinc-600">Todos os veículos exibidos já possuem ordem ou não há estoque carregado.</div>}</>}</div></section></div></div></div>}</>;
};

const OrderDetail=({order,stock,onSave,onAddService,onServiceChange,onRemoveService,serviceType,setServiceType,provider,setProvider,estimatedCost,setEstimatedCost,dueAt,setDueAt,notes,setNotes}:any)=>{const cost=order.services.reduce((a:any,s:any)=>a+(Number(s.finalCost)||Number(s.estimatedCost)||0),0);return <><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-lg font-semibold text-white">{order.plate}</span>{order.sold&&<span className="rounded-full bg-red-400/10 px-2 py-1 text-[10px] font-bold text-red-300">VENDIDO · PRIORIDADE</span>}</div><p className="mt-1 text-zinc-400">{order.vehicle}</p><p className="mt-1 text-xs text-zinc-600">{stock?`${stock.stockDays} dias de estoque · ${money(stock.cost)}`:'Veículo não localizado no snapshot atual'}</p></div><div className="grid gap-2 sm:grid-cols-2"><select value={order.status} onChange={e=>onSave({...order,status:e.target.value,completedAt:['ready','showroom','delivery','delivered'].includes(e.target.value)?new Date().toISOString():order.completedAt})} className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs text-white">{Object.entries(ORDER_LABELS).map(([k,v])=><option key={k} value={k}>{v as string}</option>)}</select><select value={order.destination} onChange={e=>onSave({...order,destination:e.target.value})} className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs text-white"><option value="showroom">Destino: Showroom</option><option value="delivery">Destino: Entrega</option></select><button onClick={()=>onSave({...order,sold:!order.sold,destination:!order.sold?'delivery':order.destination})} className={`h-10 rounded-xl border px-3 text-xs font-semibold ${order.sold?'border-red-400/20 bg-red-400/[.07] text-red-300':'border-white/10 text-zinc-300'}`}>{order.sold?'Vendido ✓':'Marcar como vendido'}</button><div className="flex h-10 items-center justify-center rounded-xl border border-white/10 bg-black/20 px-3 text-xs text-zinc-400">Custo prep. <b className="ml-2 text-white">{money(cost)}</b></div></div></div>
 <div className="mt-5 space-y-2">{order.services.map((service:any)=><div key={service.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="min-w-[180px] flex-1"><p className="font-semibold text-white">{service.type}</p><input value={service.provider||''} onChange={e=>onServiceChange(service.id,{provider:e.target.value})} placeholder="Prestador" className="mt-1 w-full bg-transparent text-xs text-zinc-500 outline-none placeholder:text-zinc-700"/></div><select value={service.status} onChange={e=>onServiceChange(service.id,{status:e.target.value,returnedAt:e.target.value==='done'?new Date().toISOString():service.returnedAt})} className="h-9 rounded-xl border border-white/10 bg-zinc-900 px-2 text-xs text-white">{Object.entries(SERVICE_LABELS).map(([k,v])=><option key={k} value={k}>{v as string}</option>)}</select><label className="text-[10px] text-zinc-600">Previsão<input type="date" value={dateValue(service.dueAt)} onChange={e=>onServiceChange(service.id,{dueAt:e.target.value})} className="mt-1 block h-9 rounded-xl border border-white/10 bg-zinc-900 px-2 text-xs text-white"/></label><label className="text-[10px] text-zinc-600">Custo final<input type="number" value={service.finalCost||''} onChange={e=>onServiceChange(service.id,{finalCost:Number(e.target.value)||0})} className="mt-1 block h-9 w-28 rounded-xl border border-white/10 bg-zinc-900 px-2 text-xs text-white"/></label><button onClick={()=>onRemoveService(service.id)} title="Remover serviço" className="grid h-9 w-9 place-items-center rounded-xl border border-red-400/10 text-red-300"><Trash2 size={14}/></button></div>{service.notes&&<p className="mt-2 text-xs text-zinc-600">{service.notes}</p>}</div>)}{!order.services.length&&<div className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-zinc-600">Nenhum serviço incluído. Faça a triagem e adicione somente o necessário.</div>}</div>
 <div className="mt-5 rounded-2xl border border-amber-400/10 bg-amber-400/[.035] p-4"><p className="text-xs font-semibold uppercase tracking-[.13em] text-amber-300">Adicionar serviço</p><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-5"><select value={serviceType} onChange={e=>setServiceType(e.target.value)} className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs text-white">{SERVICE_TYPES.map(t=><option key={t}>{t}</option>)}</select><input value={provider} onChange={e=>setProvider(e.target.value)} placeholder="Prestador" className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs text-white outline-none"/><input type="number" value={estimatedCost} onChange={e=>setEstimatedCost(e.target.value)} placeholder="Orçamento R$" className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs text-white outline-none"/><input type="date" value={dueAt} onChange={e=>setDueAt(e.target.value)} className="h-10 rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs text-white"/><button onClick={onAddService} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-amber-300 px-4 text-xs font-bold text-black"><Plus size={14}/> Adicionar</button></div><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observação do serviço" className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-zinc-900 px-3 text-xs text-white outline-none"/></div></>};
const Metric=({icon,label,value,note,warn,danger}:{icon:React.ReactNode;label:string;value:string;note:string;warn?:boolean;danger?:boolean})=><div className={`rounded-[22px] border p-4 ${danger?'border-red-400/20 bg-red-400/[.05]':warn?'border-amber-400/20 bg-amber-400/[.05]':'border-white/10 bg-white/[.03]'}`}><div className="flex items-center gap-2 text-zinc-500">{icon}<p className="text-xs">{label}</p></div><p className="mt-2 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-[11px] text-zinc-600">{note}</p></div>;
export default PrepTrackPanel;