import React, { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { BarChart3, Download, X } from 'lucide-react';
import { ShowroomPassage } from '../types';
import { showroomFlowService } from '../services/showroomFlowService';

type Props={companyId:string;storeId:string;storeName:string};
type Period='today'|'7d'|'30d'|'custom';
const origin=(i:ShowroomPassage)=>i.origin==='requested'?'requested':'walk_in';
const dt=(v?:string)=>v?new Date(v).getTime():0;
const pct=(n:number,d:number)=>d?`${((n/d)*100).toFixed(1)}%`:'0,0%';
const csvCell=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;
const startOfDay=(d:Date)=>{const x=new Date(d);x.setHours(0,0,0,0);return x;};

const ShowroomReports:React.FC<Props>=({companyId,storeId,storeName})=>{
 const[open,setOpen]=useState(false);const[items,setItems]=useState<ShowroomPassage[]>([]);const[period,setPeriod]=useState<Period>('30d');const[seller,setSeller]=useState('');const[from,setFrom]=useState('');const[to,setTo]=useState('');const[portalHost,setPortalHost]=useState<HTMLElement|null>(null);
 useEffect(()=>showroomFlowService.subscribeStorePassages(companyId,storeId,setItems,console.error),[companyId,storeId]);
 useEffect(()=>{
   const locate=()=>{
     const title=Array.from(document.querySelectorAll('h2')).find(el=>String(el.textContent||'').includes('ShowroomFlow · Passagens')) as HTMLElement|undefined;
     const header=title?.closest('header') as HTMLElement|null;
     if(!header){setPortalHost(null);return;}
     let host=header.querySelector('[data-showroom-reports-host]') as HTMLElement|null;
     if(!host){host=document.createElement('div');host.setAttribute('data-showroom-reports-host','true');host.className='ml-auto mr-2';const closeButton=header.querySelector('button');if(closeButton)header.insertBefore(host,closeButton);else header.appendChild(host);}
     setPortalHost(host);
   };
   locate();
   const observer=new MutationObserver(locate);observer.observe(document.body,{childList:true,subtree:true});
   return()=>{observer.disconnect();setPortalHost(null);};
 },[]);
 const sellers=useMemo(()=>Array.from(new Map(items.map(i=>[i.assignedSellerEmail,i.assignedSellerName])).entries()).sort((a,b)=>a[1].localeCompare(b[1])),[items]);
 const filtered=useMemo(()=>{const now=new Date();let start=0,end=Infinity;if(period==='today')start=startOfDay(now).getTime();if(period==='7d'){const d=startOfDay(now);d.setDate(d.getDate()-6);start=d.getTime();}if(period==='30d'){const d=startOfDay(now);d.setDate(d.getDate()-29);start=d.getTime();}if(period==='custom'){start=from?new Date(`${from}T00:00:00`).getTime():0;end=to?new Date(`${to}T23:59:59`).getTime():Infinity;}return items.filter(i=>dt(i.createdAt)>=start&&dt(i.createdAt)<=end&&(!seller||i.assignedSellerEmail===seller));},[items,period,seller,from,to]);
 const walk=filtered.filter(i=>origin(i)==='walk_in'),req=filtered.filter(i=>origin(i)==='requested'),sales=filtered.filter(i=>i.status==='sale'),evals=filtered.filter(i=>['evaluation','proposal','sale'].includes(i.status)),props=filtered.filter(i=>['proposal','sale'].includes(i.status)),lost=filtered.filter(i=>i.status==='no_deal');
 const assumed=filtered.filter(i=>i.assumedAt);const avgWait=assumed.length?Math.round(assumed.reduce((s,i)=>s+Math.max(0,(dt(i.assumedAt)-dt(i.createdAt))/60000),0)/assumed.length):0;const over5=assumed.filter(i=>(dt(i.assumedAt)-dt(i.createdAt))/60000>5).length,over10=assumed.filter(i=>(dt(i.assumedAt)-dt(i.createdAt))/60000>10).length;
 const bySeller=useMemo(()=>{const m=new Map<string,ShowroomPassage[]>();filtered.forEach(i=>m.set(i.assignedSellerName,[...(m.get(i.assignedSellerName)||[]),i]));return Array.from(m.entries()).map(([name,arr])=>({name,total:arr.length,walk:arr.filter(i=>origin(i)==='walk_in').length,req:arr.filter(i=>origin(i)==='requested').length,eval:arr.filter(i=>['evaluation','proposal','sale'].includes(i.status)).length,proposal:arr.filter(i=>['proposal','sale'].includes(i.status)).length,sales:arr.filter(i=>i.status==='sale').length})).sort((a,b)=>b.sales-a.sales||b.total-a.total);},[filtered]);
 const exportCsv=()=>{const rows=[['Data','Cliente','Telefone','Interesse','Origem','Vendedor','Status','Chegada','Assumido'],...filtered.map(i=>[i.createdAt?.slice(0,10),i.customerName,i.phone,i.interestModel,origin(i)==='requested'?'PEDIDO':'PASSAGEM',i.assignedSellerName,i.status,i.createdAt,i.assumedAt||''])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`showroomflow-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);};
 const trigger=<button onClick={()=>setOpen(true)} className="rounded-xl border border-violet-400/20 bg-violet-400/[.06] px-4 py-2 text-xs font-bold text-violet-200 transition hover:border-violet-300/40 hover:bg-violet-400/[.10]"><span className="inline-flex items-center gap-2"><BarChart3 size={14}/> RELATÓRIOS</span></button>;
 return <>{portalHost&&createPortal(trigger,portalHost)}{open&&<div className="fixed inset-0 z-[520] overflow-y-auto bg-black/80 p-3 backdrop-blur-md md:p-6"><div className="mx-auto max-w-7xl rounded-[30px] border border-white/10 bg-zinc-900 p-5 text-white shadow-2xl md:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-violet-300">ShowroomFlow · Gestão</p><h2 className="mt-1 text-2xl font-semibold">Relatórios de atendimento</h2><p className="mt-1 text-sm text-zinc-400">{storeName}</p></div><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-white/5 text-zinc-400"><X size={18}/></button></div>
 <div className="mt-5 flex flex-wrap gap-2">{([['today','Hoje'],['7d','7 dias'],['30d','30 dias'],['custom','Personalizado']] as [Period,string][]).map(([v,l])=><button key={v} onClick={()=>setPeriod(v)} className={`rounded-xl px-3 py-2 text-xs font-bold ${period===v?'bg-violet-300 text-black':'border border-white/10 text-zinc-300'}`}>{l}</button>)}<select value={seller} onChange={e=>setSeller(e.target.value)} className="rounded-xl border border-white/10 bg-zinc-800 px-3 text-xs"><option value="">Todos os vendedores</option>{sellers.map(([e,n])=><option key={e} value={e}>{n}</option>)}</select>{period==='custom'&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border border-white/10 bg-zinc-800 px-3 text-xs"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border border-white/10 bg-zinc-800 px-3 text-xs"/></>}<button onClick={exportCsv} className="ml-auto rounded-xl border border-emerald-400/20 px-3 py-2 text-xs font-bold text-emerald-300"><span className="inline-flex items-center gap-2"><Download size={14}/> EXPORTAR CSV</span></button></div>
 <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{[['Clientes',filtered.length],['Passagens',walk.length],['Pedidos',req.length],['Avaliações',evals.length],['Propostas',props.length],['Vendas',sales.length],['Sem negócio',lost.length],['Espera média',`${avgWait} min`]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-xs text-zinc-400">{l}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</div>
 <div className="mt-5 grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs font-bold uppercase text-zinc-500">Funil</p><div className="mt-4 space-y-3">{[['Clientes',filtered.length],['Avaliações',evals.length],['Propostas',props.length],['Vendas',sales.length]].map(([l,v],idx)=><div key={String(l)}><div className="flex justify-between text-sm"><span>{l}</span><b>{v}</b></div><div className="mt-1 h-2 rounded-full bg-white/5"><div className="h-2 rounded-full bg-violet-300" style={{width:`${filtered.length?Math.max(3,(Number(v)/filtered.length)*100):0}%`}}/></div>{idx>0&&<p className="mt-1 text-[10px] text-zinc-500">{pct(Number(v),filtered.length)} dos clientes</p>}</div>)}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs font-bold uppercase text-zinc-500">Conversão</p><p className="mt-4 text-4xl font-semibold text-emerald-300">{pct(sales.length,filtered.length)}</p><p className="text-xs text-zinc-500">cliente → venda</p><div className="mt-5 space-y-2 text-sm"><p className="flex justify-between"><span>Passagem → venda</span><b>{pct(walk.filter(i=>i.status==='sale').length,walk.length)}</b></p><p className="flex justify-between"><span>Pedido → venda</span><b>{pct(req.filter(i=>i.status==='sale').length,req.length)}</b></p></div></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs font-bold uppercase text-zinc-500">Tempo de resposta</p><p className="mt-4 text-4xl font-semibold">{avgWait} min</p><p className="text-xs text-zinc-500">média para assumir</p><div className="mt-5 space-y-2 text-sm"><p className="flex justify-between"><span>Acima de 5 min</span><b>{over5}</b></p><p className="flex justify-between"><span>Acima de 10 min</span><b className={over10?'text-red-300':''}>{over10}</b></p></div></div></div>
 <div className="mt-5 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/[.04] text-xs uppercase text-zinc-500"><tr>{['Vendedor','Atend.','Passagens','Pedidos','Avaliações','Propostas','Vendas','Conversão'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{bySeller.map(r=><tr key={r.name} className="border-t border-white/10"><td className="px-4 py-3 font-semibold">{r.name}</td><td className="px-4 py-3">{r.total}</td><td className="px-4 py-3">{r.walk}</td><td className="px-4 py-3">{r.req}</td><td className="px-4 py-3">{r.eval}</td><td className="px-4 py-3">{r.proposal}</td><td className="px-4 py-3 text-emerald-300">{r.sales}</td><td className="px-4 py-3">{pct(r.sales,r.total)}</td></tr>)}{!bySeller.length&&<tr><td colSpan={8} className="px-4 py-8 text-center text-zinc-500">Sem dados no período.</td></tr>}</tbody></table></div>
 </div></div>}</>;
};
export default ShowroomReports;